'use client';

import Link from 'next/link';
import { use, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { Asset } from '@sbaah/shared';
import { AppShell } from '@/components/layout/app-shell';
import { CreateAssetForm, assetTypeLabels } from '@/components/properties/create-asset-form';
import { CreateListingForm } from '@/components/properties/create-listing-form';
import { BackButton } from '@/components/ui/back-button';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { FormPageSkeleton } from '@/components/ui/form-page-skeleton';
import { Modal } from '@/components/ui/modal';
import { useCurrentUser } from '@/lib/auth/current-user-context';
import { archiveAsset, getAsset, getAssetRelationships, listListings, type AssetRelationships, type AssetWithMedia, type ListingWithAssets } from '@/lib/api/real-estate';

const statuses: Record<string, string> = { planned: 'مخطط', under_construction: 'تحت الإنشاء', ready: 'جاهز', maintenance: 'صيانة', inactive: 'غير نشط' };

export default function AssetDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const { me, accessToken } = useCurrentUser();
  const [asset, setAsset] = useState<AssetWithMedia | null>(null);
  const [parent, setParent] = useState<Asset | null>(null);
  const [children, setChildren] = useState<Asset[]>([]);
  const [listings, setListings] = useState<ListingWithAssets[]>([]);
  const [relationships, setRelationships] = useState<AssetRelationships | null>(null);
  const [availability,setAvailability]=useState<{status:string;reason?:string|null}|null>(null);
  const [project,setProject]=useState<{id:string;name_ar:string}|null>(null); const [phase,setPhase]=useState<{id:string;name_ar:string}|null>(null); const [unitType,setUnitType]=useState<{id:string;name_ar:string}|null>(null);
  const [notFound, setNotFound] = useState(false);
  const [showListing, setShowListing] = useState(false);
  const [showChild, setShowChild] = useState(false);

  const load = () => Promise.all([getAsset(accessToken, id), listListings(accessToken), getAssetRelationships(accessToken, id)]).then(([detail, listingResult, relationResult]) => {
    setAsset(detail.asset); setParent(detail.parent); setChildren(detail.children); setAvailability(detail.availability); setProject(detail.project); setPhase(detail.phase); setUnitType(detail.unit_type); setListings(listingResult.listings); setRelationships(relationResult.relationships);
  });

  useEffect(() => { let active = true; void load().catch(() => { if (active) setNotFound(true); }); return () => { active = false; }; }, [accessToken, id]); // eslint-disable-line react-hooks/exhaustive-deps
  const offers = useMemo(() => listings.filter(listing => (listing.listing_assets ?? []).some(relation => relation.asset_id === id)), [listings, id]);
  const sale = useMemo(() => relationships?.deals.map(link => link.deals).find(deal => deal?.status === 'won' && deal.deal_type === 'sale') ?? null, [relationships]);
  const activeLease=useMemo(()=>relationships?.leases.map(x=>x.lease_contracts).find(x=>x?.status==='active')??null,[relationships]);
  const availabilityLabels:Record<string,string>={available:'متاح',reserved:'محجوز',leased:'مؤجر',sold:'مباع',physically_unavailable:'غير متاح'};
  const saleDurationDays = sale?.closed_at ? Math.max(0, Math.ceil((new Date(sale.closed_at).getTime() - new Date(sale.listings?.created_at ?? sale.created_at).getTime()) / 86400000)) : null;

  if (notFound) return <AppShell title="العقار غير موجود" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><p className="text-text-secondary">تعذر العثور على العقار.</p></AppShell>;
  return <AppShell title={asset?.name_ar ?? 'تفاصيل العقار'} orgName={me.tenant.name_ar} accountType={me.tenant.account_type}>
    {!asset ? <FormPageSkeleton fields={6} extraCards={2} /> : <div className="mx-auto flex max-w-[900px] flex-col gap-5">
      <BackButton href="/properties" label="رجوع" className="self-start" />
      {parent && <Card className="p-4 text-sm">يتبع هذا العقار إلى <Link href={`/properties/${parent.id}`} className="font-semibold text-brand hover:underline">{parent.name_ar}</Link></Card>}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card className="p-5"><p className="text-sm text-text-secondary">نوع العقار</p><p className="mt-2 font-semibold">{assetTypeLabels[asset.asset_type]}</p></Card><Card className="p-5"><p className="text-sm text-text-secondary">الحالة الفيزيائية</p><p className="mt-2 font-semibold">{statuses[asset.physical_status]}</p></Card><Card className="p-5"><p className="text-sm text-text-secondary">الحالة التجارية</p><p className="mt-2 font-semibold">{availabilityLabels[availability?.status??'']??availability?.status??'—'}</p></Card><Card className="p-5"><p className="text-sm text-text-secondary">الرقم المرجعي</p><p className="mt-2 font-semibold">{asset.reference_number ?? '—'}</p></Card></div>
      {(project||phase||unitType)&&<Card className="p-5"><h2 className="mb-4 font-semibold">سياق المشروع</h2><div className="grid gap-4 text-sm sm:grid-cols-3"><div><p className="text-text-secondary">المشروع</p>{project?<Link href={`/projects/${project.id}`} className="font-medium text-brand hover:underline">{project.name_ar}</Link>:<p>—</p>}</div><div><p className="text-text-secondary">المرحلة</p><p className="font-medium">{phase?.name_ar??'—'}</p></div><div><p className="text-text-secondary">نوع الوحدة</p><p className="font-medium">{unitType?.name_ar??'—'}</p></div></div></Card>
      <Card className="p-6"><h2 className="mb-4 font-semibold">بيانات العقار</h2><dl className="grid gap-4 text-sm sm:grid-cols-2 md:grid-cols-3"><div><dt className="text-text-secondary">المساحة</dt><dd>{asset.area_sqm ? `${asset.area_sqm} م²` : '—'}</dd></div><div><dt className="text-text-secondary">رقم الوحدة</dt><dd>{asset.unit_number ?? '—'}</dd></div><div><dt className="text-text-secondary">رقم الدور</dt><dd>{asset.floor_number ?? '—'}</dd></div><div><dt className="text-text-secondary">غرف النوم</dt><dd>{asset.bedrooms ?? '—'}</dd></div><div><dt className="text-text-secondary">دورات المياه</dt><dd>{asset.bathrooms ?? '—'}</dd></div></dl>{asset.description_ar && <p className="mt-5 border-t border-border-subtle pt-4 text-sm text-text-secondary">{asset.description_ar}</p>}</Card>
      <Card className="overflow-hidden"><div className="flex items-start justify-between gap-3 p-5"><div><h2 className="font-semibold">العقارات التابعة</h2><p className="mt-1 text-sm text-text-secondary">مثل الشقق والأدوار والمحلات التابعة للعمارة أو المجمع.</p></div>{me.user.role !== 'agent' && <Button onClick={() => setShowChild(true)}>إضافة عقار تابع</Button>}</div>{children.length === 0 ? <p className="px-5 pb-5 text-sm text-text-secondary">لا توجد عقارات تابعة.</p> : <div className="divide-y divide-border-subtle">{children.map(child => <Link key={child.id} href={`/properties/${child.id}`} className="flex items-center justify-between px-5 py-4 hover:bg-surface-subtle-3"><span className="font-medium">{child.name_ar}</span><span className="text-sm text-text-secondary">{assetTypeLabels[child.asset_type]}{child.unit_number ? ` · ${child.unit_number}` : ''}</span></Link>)}</div>}</Card>
      {showChild && <Modal title="إضافة عقار تابع" onClose={() => setShowChild(false)}><CreateAssetForm accessToken={accessToken} parentAssetId={id} parentAssetName={asset.name_ar} onCreated={childId => { setShowChild(false); void load(); router.push(`/properties/${childId}`); }} /></Modal>}
      <Card className="overflow-hidden"><div className="flex items-start justify-between gap-3 p-5"><div><h2 className="font-semibold">العروض العقارية</h2><p className="mt-1 text-sm text-text-secondary">عروض البيع أو الإيجار المرتبطة بهذا العقار.</p></div>{me.user.role !== 'agent' && <Button onClick={() => setShowListing(true)}>إنشاء عرض</Button>}</div>{offers.length === 0 ? <p className="px-5 pb-5 text-sm text-text-secondary">لا يوجد عرض لهذا العقار.</p> : <div className="divide-y divide-border-subtle">{offers.map(offer => <Link key={offer.id} href={`/listings/${offer.id}`} className="flex justify-between px-5 py-4 hover:bg-surface-subtle-3"><span>{offer.listing_number}</span><span>{offer.listing_type === 'sale' ? 'بيع' : 'إيجار'} · {Number(offer.asking_price).toLocaleString('ar-SA')} ر.س</span></Link>)}</div>}</Card>
      {sale && <Card className="p-6"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-semibold">بيانات البيع</h2><p className="mt-1 text-sm text-text-secondary">السجل التجاري الفعلي المستمد من الصفقة المكتملة.</p></div><span className="rounded-full bg-surface-subtle px-3 py-1 text-xs font-semibold text-text-primary">تم البيع</span></div><dl className="grid gap-4 text-sm sm:grid-cols-2 md:grid-cols-3"><div><dt className="text-text-secondary">المشتري</dt><dd className="font-medium">{sale.leads?<Link href={`/leads/${sale.leads.id}`} className="text-brand hover:underline">{sale.leads.full_name}</Link>:'—'}</dd></div><div><dt className="text-text-secondary">سعر العرض</dt><dd>{sale.listings?.asking_price!=null?`${Number(sale.listings.asking_price).toLocaleString('ar-SA')} ر.س`:'—'}</dd></div><div><dt className="text-text-secondary">سعر البيع</dt><dd className="font-medium">{sale.value!=null?`${Number(sale.value).toLocaleString('ar-SA')} ر.س`:'—'}</dd></div><div><dt className="text-text-secondary">تاريخ البيع</dt><dd>{sale.closed_at?new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium'}).format(new Date(sale.closed_at)):'—'}</dd></div><div><dt className="text-text-secondary">المسؤول / الوسيط</dt><dd>{sale.users?.full_name??'—'}</dd></div><div><dt className="text-text-secondary">مصدر العميل</dt><dd>{sale.leads?.source??'—'}</dd></div><div><dt className="text-text-secondary">مدة البيع</dt><dd>{saleDurationDays!=null?`${saleDurationDays} يوم`:'—'}</dd></div><div><dt className="text-text-secondary">الصفقة</dt><dd className="font-mono text-xs">{sale.id}</dd></div><div><dt className="text-text-secondary">العرض</dt><dd>{sale.listings?.listing_number??'—'}</dd></div></dl></Card>}
      {relationships&&me.user.role!=='agent'&&<div className="grid gap-5 lg:grid-cols-2">
        <Card className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">الإيجار والإشغال</h2><p className="mt-1 text-sm text-text-secondary">العقد النشط وحالة إشغال العقار.</p></div>{activeLease&&<Link href={`/rent-plus/contracts/${activeLease.id}`} className="text-sm font-medium text-brand">فتح العقد</Link>}</div>{activeLease?<div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-text-secondary">رقم العقد</p><p className="font-medium">{activeLease.contract_number}</p></div><div><p className="text-text-secondary">قيمة العقد</p><p className="font-medium">{Number(activeLease.total_value).toLocaleString('ar-SA')} ر.س</p></div><div><p className="text-text-secondary">المدة</p><p>{activeLease.start_date} — {activeLease.end_date}</p></div><div><p className="text-text-secondary">المستأجر</p><p>{activeLease.lease_contract_parties?.find(x=>x.role==='lessee')?.parties?.name??'—'}</p></div></div>:<p className="mt-4 text-sm text-text-secondary">لا يوجد عقد إيجار نشط.</p>}</Card>
        <Card className="p-5"><h2 className="font-semibold">الملكية والإدارة</h2><div className="mt-4 space-y-3 text-sm">{relationships.ownerships.filter(x=>!x.ended_at).length?relationships.ownerships.filter(x=>!x.ended_at).map(x=><div key={x.id} className="flex justify-between gap-3"><span>{x.parties?.name??'مالك'}</span><strong>{Number(x.ownership_percentage).toLocaleString('ar-SA')}%</strong></div>):<p className="text-text-secondary">لا توجد ملكية حالية مسجلة.</p>}<div className="border-t border-border-subtle pt-3"><p className="text-text-secondary">إدارة العقار</p><p className="font-medium">{relationships.management.find(x=>x.status==='active')?'نشطة':'غير مفعلة'}</p></div></div></Card>
      </div>}
      {relationships&&me.user.role!=='agent'&&<Card className="overflow-hidden"><div className="flex items-center justify-between p-5"><div><h2 className="font-semibold">الصيانة</h2><p className="mt-1 text-sm text-text-secondary">طلبات الصيانة المرتبطة مباشرة بهذا العقار.</p></div><Link href="/rent-plus/maintenance" className="text-sm font-medium text-brand">إدارة الصيانة</Link></div>{relationships.maintenance.length===0?<p className="px-5 pb-5 text-sm text-text-secondary">لا توجد طلبات صيانة.</p>:<div className="divide-y divide-border-subtle">{relationships.maintenance.slice(0,5).map(x=><div key={x.id} className="flex items-center justify-between gap-3 px-5 py-3"><div><p className="font-medium">{x.title}</p><p className="text-xs text-text-secondary">#{x.request_number} · {x.priority}</p></div><span className="text-xs text-text-secondary">{x.status}</span></div>)}</div>}</Card>}
      {relationships && <Card className="overflow-hidden"><div className="p-5"><h2 className="font-semibold">العملاء والنشاط العقاري</h2><p className="mt-1 text-sm text-text-secondary">كل العلاقات المرتبطة بهذا العقار عبر رحلة العميل.</p></div><div className="grid grid-cols-2 gap-px border-y border-border-subtle bg-border-subtle sm:grid-cols-5">{[['مهتمون',relationships.interests.length],['معاينات',relationships.viewings.length],['حجوزات',relationships.reservations.length],['صفقات',relationships.deals.length],['عقود إيجار',relationships.leases.length]].map(([label,value])=><div key={String(label)} className="bg-surface-card p-4 text-center"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-text-secondary">{label}</p></div>)}</div><div className="divide-y divide-border-subtle">{relationships.interests.map(x=>x.leads&&<Link key={'i'+x.id} href={`/leads/${x.leads.id}`} className="flex items-center justify-between px-5 py-3 hover:bg-surface-subtle-3"><span className="font-medium">{x.leads.full_name}</span><span className="text-xs text-text-secondary">مهتم بالعقار</span></Link>)}{relationships.viewings.map(x=>x.leads&&<Link key={'v'+x.id} href={`/leads/${x.leads.id}`} className="flex items-center justify-between px-5 py-3 hover:bg-surface-subtle-3"><span className="font-medium">{x.leads.full_name}</span><span className="text-xs text-text-secondary">معاينة · {x.status}</span></Link>)}{relationships.deals.map(x=>x.deals?.leads&&<Link key={'d'+x.deal_id} href={`/leads/${x.deals.leads.id}`} className="flex items-center justify-between px-5 py-3 hover:bg-surface-subtle-3"><span className="font-medium">{x.deals.leads.full_name}</span><span className="text-xs text-text-secondary">صفقة · {x.deals.status}</span></Link>)}</div></Card>}
      {showListing && <Modal title="إنشاء عرض عقاري" onClose={() => setShowListing(false)}><CreateListingForm accessToken={accessToken} assetId={id} assetName={asset.name_ar} onCreated={listingId => router.push(`/listings/${listingId}`)} /></Modal>}
      {me.user.role !== 'agent' && <div className="flex justify-end"><Button variant="secondary" disabled={children.length > 0} title={children.length ? 'يجب نقل أو أرشفة العقارات التابعة أولًا' : undefined} onClick={async () => { if (!confirm('هل تريد أرشفة هذا العقار؟')) return; await archiveAsset(accessToken, id); router.push('/properties'); }}>أرشفة العقار</Button></div>}
    </div>}
  </AppShell>;
}
