'use client';
import{useEffect,useMemo,useState}from'react';import{useRouter}from'next/navigation';import type{Asset,AssetPhysicalStatus}from'@sbaah/shared';import{AppShell}from'@/components/layout/app-shell';import{CreateAssetForm}from'@/components/properties/create-asset-form';import{Button}from'@/components/ui/button';import{Card}from'@/components/ui/card';import{Modal}from'@/components/ui/modal';import{Select}from'@/components/ui/select';import{TableSkeleton}from'@/components/ui/table-skeleton';import{useCurrentUser}from'@/lib/auth/current-user-context';import{listAssets,listListings,type ListingWithAssets}from'@/lib/api/real-estate';

const typeLabels:Record<string,string>={apartment:'شقة',villa:'فيلا',building:'عمارة',land:'أرض',plot:'قطعة أرض',office:'مكتب',shop:'محل',warehouse:'مستودع',floor:'دور',compound:'مجمع',chalet:'شاليه',farm:'مزرعة',parking:'موقف',other:'أخرى'};
const statusLabels:Record<string,string>={planned:'مخطط',under_construction:'تحت الإنشاء',ready:'جاهز',maintenance:'صيانة',inactive:'غير نشط'};
const offerLabel=(x:ListingWithAssets)=>x.listing_type==='sale'?'للبيع':'للإيجار';

export default function PropertiesPage(){const{me,accessToken}=useCurrentUser();const router=useRouter();const[assets,setAssets]=useState<Asset[]|null>(null);const[listings,setListings]=useState<ListingWithAssets[]>([]);const[status,setStatus]=useState<AssetPhysicalStatus|''>('');const[showCreate,setShowCreate]=useState(false);const canManage=me.user.role!=='agent';
 useEffect(()=>{let active=true;void Promise.all([listAssets(accessToken,status?{physical_status:status}:{}),listListings(accessToken)]).then(([a,l])=>{if(active){setAssets(a.assets);setListings(l.listings)}});return()=>{active=false}},[accessToken,status]);
 const offers=useMemo(()=>{const m=new Map<string,ListingWithAssets[]>();for(const l of listings)for(const a of l.listing_assets??[])m.set(a.asset_id,[...(m.get(a.asset_id)??[]),l]);return m},[listings]);
 return <AppShell title="العقارات" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Select value={status} onChange={e=>setStatus(e.target.value as AssetPhysicalStatus|'')} className="w-[160px]" compact><option value="">كل الحالات</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select>{canManage&&<Button onClick={()=>setShowCreate(true)}>إضافة عقار</Button>}</div>{showCreate&&<Modal title="إضافة عقار" onClose={()=>setShowCreate(false)}><CreateAssetForm accessToken={accessToken} onCreated={id=>{setShowCreate(false);router.push(`/properties/${id}`)}}/></Modal>}<Card className="overflow-hidden">{assets===null?<TableSkeleton columns={5}/>:assets.length===0?<p className="p-8 text-center text-text-secondary">لا توجد عقارات حتى الآن</p>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-surface-header text-right text-text-secondary"><tr><th className="px-4 py-3 font-medium">العقار</th><th className="px-4 py-3 font-medium">النوع</th><th className="px-4 py-3 font-medium">الحالة الفيزيائية</th><th className="px-4 py-3 font-medium">العروض</th><th className="px-4 py-3 font-medium">المرجع</th></tr></thead><tbody>{assets.map(asset=>{const ls=offers.get(asset.id)??[];return <tr key={asset.id} className="border-border-subtle border-t"><td className="px-4 py-3"><button onClick={()=>router.push(`/properties/${asset.id}`)} className="font-medium hover:text-brand">{asset.name_ar}</button></td><td className="px-4 py-3 text-text-secondary">{typeLabels[asset.asset_type]??asset.asset_type}</td><td className="px-4 py-3">{statusLabels[asset.physical_status]??asset.physical_status}</td><td className="px-4 py-3">{ls.length===0?<span className="text-text-secondary">بدون عرض</span>:<div className="flex flex-wrap gap-1">{ls.map(l=><span key={l.id} className="rounded-full bg-surface-subtle-3 px-2 py-1 text-xs">{offerLabel(l)} · {Number(l.asking_price).toLocaleString('ar-SA')} ر.س</span>)}</div>}</td><td className="px-4 py-3 text-text-secondary">{asset.reference_number??'—'}</td></tr>})}</tbody></table></div>}</Card></AppShell>}