'use client';
import {useEffect,useMemo,useState} from 'react';
import {Card}from'@/components/ui/card';import{Select}from'@/components/ui/select';import{MediaDropzone}from'@/components/ui/media-dropzone';import{getSupabaseBrowserClient}from'@/lib/supabase/client';
import{createAssetMedia,deleteAssetMedia,listAssetMedia,updateAssetMedia,type AssetMedia,type AssetMediaCategory}from'@/lib/api/real-estate';
const categories:Array<{value:AssetMediaCategory;label:string}>=[
 {value:'general',label:'معرض الصور'},
 {value:'floor_plan',label:'مخطط العقار'},
 {value:'construction',label:'أعمال الإنشاء'},
];
const Home=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-none stroke-current" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m3 11 9-7 9 7"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>;
const Trash=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-none stroke-current" strokeWidth="1.8"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg>;
export function AssetMediaManager({assetId,tenantId,accessToken,canManage,isUnit=false}:{assetId:string;tenantId:string;accessToken:string;canManage:boolean;isUnit?:boolean}){
 const[media,setMedia]=useState<AssetMedia[]>([]),[category,setCategory]=useState<AssetMediaCategory>('general'),[busy,setBusy]=useState(false),[error,setError]=useState('');const visible=categories;
 const load=async()=>setMedia((await listAssetMedia(accessToken,assetId)).media);useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل الوسائط'))},[accessToken,assetId]);
 const groups=useMemo(()=>visible.map(c=>({...c,items:media.filter(x=>x.category===c.value).sort((a,b)=>a.order_index-b.order_index)})).filter(x=>x.items.length),[media,isUnit]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');try{const supabase=getSupabaseBrowserClient();for(const file of Array.from(files)){const type=file.type.startsWith('video/')?'video':file.type.startsWith('image/')?'image':null;if(!type)throw new Error('يسمح بالصور والفيديو فقط');const ext=file.name.split('.').pop()?.toLowerCase()||'bin',objectPath=`${tenantId}/assets/${assetId}/${crypto.randomUUID()}.${ext}`;const{error:e}=await supabase.storage.from('property-media').upload(objectPath,file,{contentType:file.type,upsert:false});if(e)throw e;const{data}=supabase.storage.from('property-media').getPublicUrl(objectPath);await createAssetMedia(accessToken,assetId,{media_type:type,category,url:data.publicUrl,order_index:media.filter(x=>x.category===category).length,is_primary:media.length===0&&type==='image'});}await load();}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الوسائط')}finally{setBusy(false)}}
 async function primary(item:AssetMedia){await updateAssetMedia(accessToken,assetId,item.id,{is_primary:true});await load()}
 async function remove(item:AssetMedia){await deleteAssetMedia(accessToken,assetId,item.id);await load()}
 return <Card className="p-4 sm:p-5 md:p-6"><div className="mb-4"><h2 className="font-semibold">{isUnit?'صور وفيديو الوحدة':'صور وفيديو العقار'}</h2><p className="mt-1 text-sm text-text-secondary">اختر نوع الوسائط، ثم أضف الصور أو الفيديو.</p><p className="mt-1 text-xs text-text-tertiary">الصور: 1200 × 900 px · JPG, PNG, WEBP · الفيديو: 1920 × 1080 px · MP4, WEBM</p></div>{canManage&&<div className="mb-5 space-y-3"><Select value={category} onChange={e=>setCategory(e.target.value as AssetMediaCategory)}>{visible.map(option=><option key={option.value} value={option.value}>{option.value==='floor_plan'&&isUnit?'مخطط الوحدة':option.label}</option>)}</Select><MediaDropzone accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple disabled={busy} hint="الصور: JPG, PNG, WEBP · 1200 × 900 px · الفيديو: MP4, WEBM · 1920 × 1080 px" onFiles={files=>void upload(files)}/></div>}{error&&<p className="mb-3 text-sm text-danger">{error}</p>}{groups.length===0?<p className="text-sm text-text-secondary">لا توجد وسائط بعد.</p>:<div className="space-y-5">{groups.map(g=><section key={g.value}><h3 className="mb-2 text-sm font-medium">{g.label} <span className="text-text-secondary">({g.items.length})</span></h3><div className="-mx-1 flex snap-x snap-mandatory gap-3 overflow-x-auto px-1 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{g.items.map(item=><div key={item.id} className={`relative w-[72%] max-w-[260px] shrink-0 snap-start overflow-hidden rounded-xl bg-surface-subtle ring-1 sm:w-[220px] ${item.is_primary?'ring-brand':'ring-border-subtle'}`}>{item.media_type==='image'?<img src={item.url} alt={item.alt_ar??g.label} className="aspect-[4/3] w-full object-cover"/>:<video src={item.url} controls preload="metadata" className="aspect-[4/3] w-full object-cover"/>}{canManage&&<div className="absolute right-2 top-2 flex items-center gap-1.5">{item.media_type==='image'&&<button type="button" title={item.is_primary?'الصورة الرئيسية':'تعيين كصورة رئيسية'} aria-label={item.is_primary?'الصورة الرئيسية':'تعيين كصورة رئيسية'} disabled={item.is_primary} onClick={()=>!item.is_primary&&void primary(item)} className={`inline-flex h-9 w-9 items-center justify-center rounded-full shadow-sm transition ${item.is_primary?'bg-brand text-white':'bg-black/55 text-white hover:bg-brand'}`}><Home/></button>}<button type="button" title="حذف" aria-label="حذف" onClick={()=>void remove(item)} className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-white/90 text-danger shadow-sm transition hover:bg-white"><Trash/></button></div>}</div>)}</div></section>)}</div>}</Card>
}