'use client';
import {useEffect,useMemo,useState} from 'react';
import {Card}from'@/components/ui/card';import{Select}from'@/components/ui/select';import{getSupabaseBrowserClient}from'@/lib/supabase/client';
import{createAssetMedia,deleteAssetMedia,listAssetMedia,updateAssetMedia,type AssetMedia,type AssetMediaCategory}from'@/lib/api/real-estate';
const categories:Array<{value:AssetMediaCategory;label:string}>=[
 {value:'general',label:'معرض الصور'},
 {value:'floor_plan',label:'مخطط العقار'},
 {value:'construction',label:'أعمال الإنشاء'},
];
const Star=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-current"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>;
const Trash=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-none stroke-current" strokeWidth="1.8"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg>;
export function AssetMediaManager({assetId,tenantId,accessToken,canManage,isUnit=false}:{assetId:string;tenantId:string;accessToken:string;canManage:boolean;isUnit?:boolean}){
 const[media,setMedia]=useState<AssetMedia[]>([]),[category,setCategory]=useState<AssetMediaCategory>('general'),[busy,setBusy]=useState(false),[error,setError]=useState('');const visible=categories;
 const load=async()=>setMedia((await listAssetMedia(accessToken,assetId)).media);useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل الوسائط'))},[accessToken,assetId]);
 const groups=useMemo(()=>visible.map(c=>({...c,items:media.filter(x=>x.category===c.value).sort((a,b)=>a.order_index-b.order_index)})).filter(x=>x.items.length),[media,isUnit]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');try{const supabase=getSupabaseBrowserClient();for(const file of Array.from(files)){const type=file.type.startsWith('video/')?'video':file.type.startsWith('image/')?'image':null;if(!type)throw new Error('يسمح بالصور والفيديو فقط');const ext=file.name.split('.').pop()?.toLowerCase()||'bin',objectPath=`${tenantId}/assets/${assetId}/${crypto.randomUUID()}.${ext}`;const{error:e}=await supabase.storage.from('property-media').upload(objectPath,file,{contentType:file.type,upsert:false});if(e)throw e;const{data}=supabase.storage.from('property-media').getPublicUrl(objectPath);await createAssetMedia(accessToken,assetId,{media_type:type,category,url:data.publicUrl,order_index:media.filter(x=>x.category===category).length,is_primary:media.length===0&&type==='image'});}await load();}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الوسائط')}finally{setBusy(false)}}
 async function primary(item:AssetMedia){await updateAssetMedia(accessToken,assetId,item.id,{is_primary:true});await load()}
 async function remove(item:AssetMedia){await deleteAssetMedia(accessToken,assetId,item.id);await load()}
 return <Card className="p-4 sm:p-5 md:p-6"><div className="mb-4"><h2 className="font-semibold">{isUnit?'صور وفيديو الوحدة':'صور وفيديو العقار'}</h2><p className="mt-1 text-sm text-text-secondary">اختر نوع الوسائط، ثم أضف الصور أو الفيديو.</p><p className="mt-1 text-xs text-text-tertiary">الصور: 1200 × 900 px · JPG, PNG, WEBP · الفيديو: 1920 × 1080 px · MP4, WEBM</p></div>{canManage&&<div className="mb-5 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><Select value={category} onChange={e=>setCategory(e.target.value as AssetMediaCategory)}/><label className="inline-flex h-10 w-full cursor-pointer items-center justify-center rounded-input bg-brand px-4 text-sm font-medium text-white sm:w-44"><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple disabled={busy} onChange={e=>{void upload(e.target.files);e.currentTarget.value=''}}/>{busy?'جارٍ الرفع...':'＋ إضافة وسائط'}</label></div>}{error&&<p className="mb-3 text-sm text-danger">{error}</p>}{groups.length===0?<p className="text-sm text-text-secondary">لا توجد وسائط بعد.</p>:<div className="space-y-5">{groups.map(g=><section key={g.value}><h3 className="mb-2 text-sm font-medium">{g.label} <span className="text-text-secondary">({g.items.length})</span></h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{g.items.map(item=><div key={item.id} className={`relative overflow-hidden rounded-xl border-2 bg-surface-card ${item.is_primary?'border-brand':'border-transparent ring-1 ring-border-subtle'}`}>{item.media_type==='image'?<img src={item.url} alt={item.alt_ar??g.label} className="aspect-[4/3] w-full object-cover"/>:<video src={item.url} controls preload="metadata" className="aspect-[4/3] w-full object-cover"/>}{item.is_primary&&<span title="الصورة الرئيسية" className="absolute right-2 top-2 inline-flex h-7 w-7 items-center justify-center rounded-full bg-brand text-white shadow"><Star/></span>}{canManage&&<div className="grid grid-cols-2 gap-1.5 p-2">{item.media_type==='image'&&!item.is_primary?<button type="button" onClick={()=>void primary(item)} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-input border border-border-default text-xs font-medium text-text-secondary hover:border-brand hover:text-brand"><Star/>تعيين رئيسية</button>:<span/>}<button type="button" onClick={()=>void remove(item)} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-input border border-border-default text-xs font-medium text-text-secondary hover:text-danger"><Trash/>حذف</button></div>}</div>)}</div></section>)}</div>}</Card>
}