'use client';
import {useEffect,useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';import{Card}from'@/components/ui/card';import{Select}from'@/components/ui/select';import{getSupabaseBrowserClient}from'@/lib/supabase/client';
import{createAssetMedia,deleteAssetMedia,listAssetMedia,updateAssetMedia,type AssetMedia,type AssetMediaCategory}from'@/lib/api/real-estate';
const categories: Array<{ value: AssetMediaCategory; label: string }> = [
  { value: 'general', label: 'صور العقار' }, { value: 'exterior', label: 'الواجهة الخارجية' },
  { value: 'entrance', label: 'المدخل' }, { value: 'living', label: 'المجلس / الصالة' },
  { value: 'bedrooms', label: 'غرف النوم' }, { value: 'kitchen', label: 'المطبخ' },
  { value: 'bathrooms', label: 'دورات المياه' }, { value: 'outdoor', label: 'المساحات الخارجية' },
  { value: 'amenities', label: 'المرافق' }, { value: 'parking', label: 'المواقف' },
  { value: 'floor_plan', label: 'المخطط' }, { value: 'location', label: 'الموقع والمحيط' },
  { value: 'view', label: 'الإطلالة' }, { value: 'construction', label: 'مراحل الإنشاء' },
  { value: 'other', label: 'أخرى' },
];
export function AssetMediaManager({assetId,tenantId,accessToken,canManage,isUnit=false}:{assetId:string;tenantId:string;accessToken:string;canManage:boolean;isUnit?:boolean}){
 const[media,setMedia]=useState<AssetMedia[]>([]),[category,setCategory]=useState<AssetMediaCategory>('general'),[busy,setBusy]=useState(false),[error,setError]=useState('');const visible=categories.filter(c=>!isUnit||!['exterior','entrance','parking','construction'].includes(c.value));
 const load=async()=>setMedia((await listAssetMedia(accessToken,assetId)).media);useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل الوسائط'))},[accessToken,assetId]);
 const groups=useMemo(()=>visible.map(c=>({...c,items:media.filter(x=>x.category===c.value).sort((a,b)=>a.order_index-b.order_index)})).filter(x=>x.items.length),[media,isUnit]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');try{const supabase=getSupabaseBrowserClient();for(const file of Array.from(files)){const type=file.type.startsWith('video/')?'video':file.type.startsWith('image/')?'image':null;if(!type)throw new Error('يسمح بالصور والفيديو فقط');const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const objectPath=`${tenantId}/assets/${assetId}/${crypto.randomUUID()}.${ext}`;const{error:e}=await supabase.storage.from('property-media').upload(objectPath,file,{contentType:file.type,upsert:false});if(e)throw e;const{data}=supabase.storage.from('property-media').getPublicUrl(objectPath);await createAssetMedia(accessToken,assetId,{media_type:type,category,url:data.publicUrl,order_index:media.filter(x=>x.category===category).length,is_primary:media.length===0&&type==='image'});}await load();}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الوسائط')}finally{setBusy(false)}}
 return <Card className="p-5 md:p-6"><div className="mb-4"><h2 className="font-semibold">{isUnit?'صور وفيديو الوحدة':'صور وفيديو العقار'}</h2><p className="mt-1 text-sm text-text-secondary">اختر نوع الوسائط، وستظهر للزائر بالترتيب العقاري المناسب.</p><p className="mt-1 text-xs text-text-tertiary">الصور: 1200 × 900 px · JPG, PNG, WEBP · الفيديو: 1920 × 1080 px · MP4, WEBM</p></div>{canManage&&<div className="mb-5 grid gap-3 sm:grid-cols-[1fr_auto]"><Select value={category} onChange={e=>setCategory(e.target.value as AssetMediaCategory)}>{visible.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</Select><label className="inline-flex cursor-pointer items-center justify-center rounded-input bg-brand px-4 py-2 text-sm font-medium text-white"><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple disabled={busy} onChange={e=>{void upload(e.target.files);e.currentTarget.value=''}}/>{busy?'جارٍ الرفع...':'＋ إضافة صور أو فيديو'}</label></div>}{error&&<p className="mb-3 text-sm text-danger">{error}</p>}{groups.length===0?<p className="text-sm text-text-secondary">لا توجد وسائط بعد.</p>:<div className="space-y-5">{groups.map(g=><section key={g.value}><h3 className="mb-2 text-sm font-medium">{g.label} <span className="text-text-secondary">({g.items.length})</span></h3><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{g.items.map(item=><div key={item.id} className="overflow-hidden rounded-xl border border-border-subtle">{item.media_type==='image'?<img src={item.url} alt={item.alt_ar??g.label} className="aspect-[4/3] w-full object-cover"/>:<video src={item.url} controls preload="metadata" className="aspect-[4/3] w-full object-cover"/>}<div className="flex flex-wrap gap-1 p-2">{item.is_primary&&<span className="text-[11px] font-medium text-brand">رئيسية</span>}{canManage&&item.media_type==='image'&&!item.is_primary&&<Button variant="secondary" onClick={async()=>{await updateAssetMedia(accessToken,assetId,item.id,{is_primary:true});await load()}}>رئيسية</Button>}{canManage&&<Button variant="secondary" onClick={async()=>{await deleteAssetMedia(accessToken,assetId,item.id);await load()}}><span aria-hidden="true">⌫</span> حذف</Button>}</div></div>)}</div></section>)}</div>}</Card>
}