'use client';
import{useEffect,useMemo,useState}from'react';
import{Button}from'@/components/ui/button';
import{Input}from'@/components/ui/input';
import{Select}from'@/components/ui/select';
import{generateInstallments,listInstallments,listLeaseContracts,recordLeasePayment,type InstallmentRow,type LeaseContractRow}from'@/lib/api/rent-plus';

export function RecordPaymentForm({accessToken,onCreated}:{accessToken:string;onCreated:()=>void}){
 const[c,setC]=useState<LeaseContractRow[]>([]);const[contractId,setContractId]=useState('');const[i,setI]=useState<InstallmentRow[]>([]);const[installmentId,setInstallmentId]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{void listLeaseContracts(accessToken).then(r=>setC(r.contracts))},[accessToken]);
 useEffect(()=>{if(!contractId){setI([]);return}void listInstallments(accessToken,contractId).then(r=>setI(r.installments))},[accessToken,contractId]);
 const selected=useMemo(()=>i.find(x=>x.id===installmentId),[i,installmentId]);
 async function createSchedule(){if(!contractId)return;setBusy(true);setError('');try{const r=await generateInstallments(accessToken,contractId);setI(r.installments)}catch(x){setError(x instanceof Error?x.message:'تعذر إنشاء جدول الاستحقاقات')}finally{setBusy(false)}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const amount=Number(f.get('amount'));if(!installmentId){setError('اختر الاستحقاق');return}if(selected&&amount>selected.remaining_amount){setError('المبلغ أكبر من المتبقي على الاستحقاق');return}setBusy(true);setError('');try{await recordLeasePayment(accessToken,{payment_number:f.get('payment_number'),contract_id:contractId,amount,payment_method:f.get('payment_method'),reference_number:f.get('reference_number')||null,allocations:[{installment_id:installmentId,amount}]});onCreated()}catch(x){setError(x instanceof Error?x.message:'تعذر تسجيل الدفعة')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="space-y-4"><Input name="payment_number" placeholder="رقم الدفعة" required/><Select name="contract_id" className="w-full" required value={contractId} onChange={e=>{setContractId(e.target.value);setInstallmentId('')}}><option value="">اختر العقد</option>{c.map(x=><option key={x.id} value={x.id}>{x.contract_number}</option>)}</Select>{contractId&&i.length===0&&<div className="rounded-lg border p-4 text-sm"><p className="mb-3">لا يوجد جدول استحقاقات لهذا العقد.</p><Button type="button" variant="secondary" disabled={busy} onClick={createSchedule}>إنشاء جدول الاستحقاقات</Button></div>}{i.length>0&&<Select className="w-full" value={installmentId} onChange={e=>setInstallmentId(e.target.value)} required><option value="">اختر الاستحقاق</option>{i.filter(x=>x.status!=='paid'&&x.status!=='cancelled').map(x=><option key={x.id} value={x.id}>دفعة {x.installment_number} — {x.due_date} — المتبقي {Number(x.remaining_amount).toLocaleString('ar-SA')} ر.س</option>)}</Select>}{selected&&<div className="grid grid-cols-3 gap-2 rounded-lg border p-3 text-center text-xs"><div><span className="block text-text-secondary">القيمة</span>{Number(selected.amount).toLocaleString('ar-SA')}</div><div><span className="block text-text-secondary">المدفوع</span>{Number(selected.paid_amount).toLocaleString('ar-SA')}</div><div><span className="block text-text-secondary">المتبقي</span>{Number(selected.remaining_amount).toLocaleString('ar-SA')}</div></div>}<Input name="amount" type="number" min="0.01" max={selected?.remaining_amount} step="0.01" placeholder="المبلغ" required/><Select name="payment_method" className="w-full"><option value="bank_transfer">تحويل بنكي</option><option value="cash">نقدي</option><option value="card">بطاقة</option><option value="sadad">سداد</option><option value="other">أخرى</option></Select><Input name="reference_number" placeholder="رقم المرجع"/>{error&&<p className="text-sm text-red-600">{error}</p>}<Button type="submit" disabled={busy||!installmentId}>{busy?'جارٍ الحفظ...':'تسجيل الدفعة'}</Button></form>
}