import { z } from 'zod';import { DEAL_STATUSES } from '@sbaah/shared';
import { ApiError,okResponse,withErrorHandling, databaseWriteError } from '@/lib/http';import { getAuthenticatedClient } from '@/lib/auth/get-authenticated-client';import { getCallerContext } from '@/lib/auth/get-caller-context';import { assertPermission } from '@/lib/auth/permissions';import { isAssignedScope } from '@/lib/auth/crm-scope';
const updateSchema=z.object({status:z.enum(DEAL_STATUSES).optional(),value:z.number().nonnegative().optional().nullable(),expected_close_date:z.string().date().optional().nullable(),lost_reason:z.string().trim().optional().nullable(),commission_value:z.number().nonnegative().optional().nullable()}).refine(v=>Object.keys(v).length>0).superRefine((v,ctx)=>{if(v.status==='lost'&&!v.lost_reason?.trim())ctx.addIssue({code:z.ZodIssueCode.custom,path:['lost_reason'],message:'سبب خسارة الصفقة مطلوب'});});
interface RouteContext{params:Promise<{id:string}>}
export const GET=withErrorHandling<RouteContext>(async(request,{params})=>{const{id}=await params;const{supabase}=getAuthenticatedClient(request);const c=await getCallerContext(supabase);const grant=assertPermission(c.role,'crm.read');let q=supabase.from('deals').select('*,deal_assets(asset_id,assets(*))').eq('id',id).eq('tenant_id',c.tenantId);if(isAssignedScope(grant))q=q.eq('responsible_user_id',c.userId);const{data,error}=await q.maybeSingle();if(error)throw new Error(error.message);if(!data)throw new ApiError(404,'deal_not_found','الصفقة غير موجودة');return okResponse({deal:data});});
export const PATCH=withErrorHandling<RouteContext>(async(request,{params})=>{
 const{id}=await params;const{supabase}=getAuthenticatedClient(request);const c=await getCallerContext(supabase);const grant=assertPermission(c.role,'crm.update');const input=updateSchema.parse(await request.json());
 if(isAssignedScope(grant)){const{data:owned,error:ownedError}=await supabase.from('deals').select('id').eq('id',id).eq('tenant_id',c.tenantId).eq('responsible_user_id',c.userId).maybeSingle();if(ownedError)throw new Error(ownedError.message);if(!owned)throw new ApiError(404,'deal_not_found','الصفقة غير موجودة');}
 const{data:current,error:currentError}=await supabase.from('deals').select('status,deal_type').eq('id',id).eq('tenant_id',c.tenantId).maybeSingle();if(currentError)throw new Error(currentError.message);if(!current)throw new ApiError(404,'deal_not_found','الصفقة غير موجودة');
 if(['won','lost'].includes(current.status))throw new ApiError(409,'deal_already_closed','لا يمكن تعديل صفقة مغلقة');
 if(input.status==='won'){
  if(current.deal_type==='sale'){const{data,error}=await supabase.rpc('close_sale_deal',{p_deal_id:id,p_sale_value:input.value??null}).single();if(error)throw databaseWriteError(error,'Failed to update deal');return okResponse({deal:data});}
 }
 let q=supabase.from('deals').update(input).eq('id',id).eq('tenant_id',c.tenantId);if(isAssignedScope(grant))q=q.eq('responsible_user_id',c.userId);const{data,error}=await q.select().maybeSingle();if(error)throw databaseWriteError(error,'Failed to update deal');if(!data)throw new ApiError(404,'deal_not_found','الصفقة غير موجودة');return okResponse({deal:data});
});