'use client';
import {useEffect,useMemo,useState} from 'react';
import {Card} from '@/components/ui/card';
import {Select} from '@/components/ui/select';
import {MediaDropzone} from '@/components/ui/media-dropzone';
import {getSupabaseBrowserClient} from '@/lib/supabase/client';
import {createProjectMedia,deleteProjectMedia,listProjectMedia,updateProjectMedia,type ProjectMedia,type ProjectMediaCategory} from '@/lib/api/hierarchy';

const Home=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-none stroke-current" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m3 11 9-7 9 7"/><path d="M5 10v10h14V10M9 20v-6h6v6"/></svg>;
const Trash=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5 fill-none stroke-current" strokeWidth="1.8"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg>;
const categories:Array<{value:ProjectMediaCategory;label:string;hint:string}>=[
 {value:'general',label:'معرض الصور',hint:'الصور العامة وأفضل اللقطات للمشروع'},
 {value:'master_plan',label:'مخطط المشروع',hint:'المخطط العام للمشروع'},
 {value:'construction',label:'أعمال الإنشاء',hint:'صور تقدم وتنفيذ أعمال الإنشاء'},
];
export function ProjectMediaManager({projectId,tenantId,accessToken,canManage}:{projectId:string;tenantId:string;accessToken:string;canManage:boolean}){
 const[media,setMedia]=useState<ProjectMedia[]>([]),[category,setCategory]=useState<ProjectMediaCategory>('general'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{const r=await listProjectMedia(accessToken,projectId);setMedia(r.media)};
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل الوسائط'))},[accessToken,projectId]);
 const groups=useMemo(()=>categories.map(c=>({...c,items:media.filter(x=>x.category===c.value).sort((a,b)=>a.order_index-b.order_index)})).filter(g=>g.items.length),[media]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');try{const supabase=getSupabaseBrowserClient();for(const file of Array.from(files)){const type=file.type.startsWith('image/')?'image':null;if(!type)throw new Error('يسمح برفع الصور فقط');const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const objectPath=`${tenantId}/projects/${projectId}/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabase.storage.from('property-media').upload(objectPath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const{data}=supabase.storage.from('property-media').getPublicUrl(objectPath);const sameCategory=media.filter(x=>x.category===category);await createProjectMedia(accessToken,projectId,{media_type:type,category,url:data.publicUrl,alt_ar:null,alt_en:null,order_index:sameCategory.length,is_primary:media.length===0&&type==='image'});}await load();}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الوسائط')}finally{setBusy(false)}}
 async function remove(item:ProjectMedia){await deleteProjectMedia(accessToken,projectId,item.id);await load()}
 async function primary(item:ProjectMedia){await updateProjectMedia(accessToken,projectId,item.id,{is_primary:true});await load()}
 return <Card className="p-5 md:p-6"><div className="mb-5"><h2 className="font-semibold">وسائط المشروع</h2><p className="mt-1 text-sm text-text-secondary">أضف الوسائط ضمن الأقسام الثلاثة، وسيظهر في موقع العميل فقط القسم الذي يحتوي على صور.</p><p className="mt-1 text-xs text-text-tertiary">1200 × 900 px · JPG, PNG, WEBP</p></div>{canManage&&<div className="mb-6 space-y-3"><div><Select value={category} onChange={e=>setCategory(e.target.value as ProjectMediaCategory)}>{categories.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</Select><p className="mt-2 text-xs text-text-secondary">{categories.find(c=>c.value===category)?.hint}</p></div><MediaDropzone accept="image/jpeg,image/png,image/webp" multiple disabled={busy} hint="JPG, PNG, WEBP · 1200 × 900 px" onFiles={files=>void upload(files)}/></div>}{error&&<p className="mb-4 text-sm text-danger">{error}</p>}{groups.length===0?<p className="text-sm text-text-secondary">لم تتم إضافة وسائط للمشروع بعد.</p>:<div className="space-y-6">{groups.map(group=><section key={group.value}><div className="mb-3 flex items-center gap-2"><h3 className="font-medium">{group.label}</h3><span className="text-xs text-text-secondary">({group.items.length})</span></div><div className="-mx-1 flex snap-x snap-mandatory gap-3 overflow-x-auto px-1 pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{group.items.map(item=><div key={item.id} className={`group relative w-[46%] max-w-[190px] shrink-0 snap-start overflow-hidden rounded-xl bg-surface-subtle ring-1 sm:w-[220px] ${item.is_primary?'ring-brand':'ring-border-subtle'}`}>{item.media_type==='image'?<img src={item.url} alt={item.alt_ar??group.label} className="aspect-[4/3] w-full object-cover"/>:<video src={item.url} className="aspect-[4/3] w-full object-cover" controls preload="metadata"/>}{canManage&&<div className="absolute right-2 top-2 flex items-center gap-1.5">{item.media_type==='image'&&<button type="button" title={item.is_primary?'الصورة الرئيسية':'تعيين كصورة رئيسية'} aria-label={item.is_primary?'الصورة الرئيسية':'تعيين كصورة رئيسية'} disabled={item.is_primary} onClick={()=>!item.is_primary&&void primary(item)} className={`inline-flex h-8 w-8 items-center justify-center rounded-full shadow-sm transition ${item.is_primary?'bg-brand text-white':'bg-black/55 text-white hover:bg-brand'}`}><Home/></button>}<button type="button" title="حذف" aria-label="حذف" onClick={()=>void remove(item)} className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white/90 text-danger shadow-sm transition hover:bg-white"><Trash/></button></div>}</div>)}</div></section>)}</div>}</Card>;
}