'use client';
import {useEffect,useMemo,useState} from 'react';
import {Card} from '@/components/ui/card';
import {Select} from '@/components/ui/select';
import {getSupabaseBrowserClient} from '@/lib/supabase/client';
import {createProjectMedia,deleteProjectMedia,listProjectMedia,updateProjectMedia,type ProjectMedia,type ProjectMediaCategory} from '@/lib/api/hierarchy';

const Star=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-current"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>;
const Trash=()=> <svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-none stroke-current" strokeWidth="1.8"><path d="M4 7h16M9 7V4h6v3m3 0-1 13H7L6 7m4 4v5m4-5v5"/></svg>;
const categories:Array<{value:ProjectMediaCategory;label:string;hint:string}>=[
 {value:'general',label:'معرض الصور',hint:'الصور العامة وأفضل اللقطات للمشروع'},
 {value:'master_plan',label:'مخطط المشروع',hint:'المخطط العام للمشروع'},
 {value:'construction',label:'أعمال الإنشاء',hint:'صور تقدم وتنفيذ أعمال الإنشاء'},
];
export function ProjectMediaManager({projectId,tenantId,accessToken,canManage}:{projectId:string;tenantId:string;accessToken:string;canManage:boolean}){
 const[media,setMedia]=useState<ProjectMedia[]>([]),[category,setCategory]=useState<ProjectMediaCategory>('general'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{const r=await listProjectMedia(accessToken,projectId);setMedia(r.media)};
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل الوسائط'))},[accessToken,projectId]);
 const groups=useMemo(()=>categories.map(c=>({...c,items:media.filter(x=>x.category===c.value).sort((a,b)=>a.order_index-b.order_index)})).filter(g=>g.items.length),[media]);
 async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setError('');try{const supabase=getSupabaseBrowserClient();for(const file of Array.from(files)){const type=file.type.startsWith('image/')?'image':null;if(!type)throw new Error('يسمح برفع الصور فقط');const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const objectPath=`${tenantId}/projects/${projectId}/${crypto.randomUUID()}.${ext}`;const{error:uploadError}=await supabase.storage.from('property-media').upload(objectPath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const{data}=supabase.storage.from('property-media').getPublicUrl(objectPath);const sameCategory=media.filter(x=>x.category===category);await createProjectMedia(accessToken,projectId,{media_type:type,category,url:data.publicUrl,alt_ar:null,alt_en:null,order_index:sameCategory.length,is_primary:media.length===0&&type==='image'});}await load();}catch(e){setError(e instanceof Error?e.message:'تعذر رفع الوسائط')}finally{setBusy(false)}}
 async function remove(item:ProjectMedia){await deleteProjectMedia(accessToken,projectId,item.id);await load()}
 async function primary(item:ProjectMedia){await updateProjectMedia(accessToken,projectId,item.id,{is_primary:true});await load()}
 return <Card className="p-5 md:p-6"><div className="mb-5"><h2 className="font-semibold">وسائط المشروع</h2><p className="mt-1 text-sm text-text-secondary">أضف الوسائط ضمن الأقسام الثلاثة، وسيظهر في موقع العميل فقط القسم الذي يحتوي على صور.</p><p className="mt-1 text-xs text-text-tertiary">1200 × 900 px · JPG, PNG, WEBP</p></div>{canManage&&<div className="mb-6 grid gap-3 rounded-xl border border-border-subtle p-4 sm:grid-cols-[1fr_auto]"><div><Select value={category} onChange={e=>setCategory(e.target.value as ProjectMediaCategory)}>{categories.map(c=><option key={c.value} value={c.value}>{c.label}</option>)}</Select><p className="mt-2 text-xs text-text-secondary">{categories.find(c=>c.value===category)?.hint}</p></div><label className="inline-flex h-10 w-full cursor-pointer items-center justify-center rounded-input bg-brand px-4 text-sm font-medium text-white sm:w-44"><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{void upload(e.target.files);e.currentTarget.value=''}}/>{busy?'جارٍ الرفع...':'＋ إضافة صور'}</label></div>}{error&&<p className="mb-4 text-sm text-danger">{error}</p>}{groups.length===0?<p className="text-sm text-text-secondary">لم تتم إضافة وسائط للمشروع بعد.</p>:<div className="space-y-6">{groups.map(group=><section key={group.value}><div className="mb-3 flex items-center gap-2"><h3 className="font-medium">{group.label}</h3><span className="text-xs text-text-secondary">({group.items.length})</span></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{group.items.map(item=><div key={item.id} className={`relative overflow-hidden rounded-xl border-2 bg-surface-card ${item.is_primary?'border-brand':'border-transparent ring-1 ring-border-subtle'}`}>{item.media_type==='image'?<img src={item.url} alt={item.alt_ar??group.label} className="aspect-[4/3] w-full object-cover"/>:<video src={item.url} className="aspect-[4/3] w-full object-cover" controls preload="metadata"/>}{item.is_primary&&<span title="الصورة الرئيسية" className="absolute right-2 top-2 inline-flex h-7 w-7 items-center justify-center rounded-full bg-brand text-white shadow"><Star/></span>}{canManage&&<div className="grid grid-cols-2 gap-1.5 p-2">{item.media_type==='image'&&!item.is_primary?<button type="button" onClick={()=>void primary(item)} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-input border border-border-default text-xs font-medium text-text-secondary hover:border-brand hover:text-brand"><Star/>تعيين رئيسية</button>:<span/>}<button type="button" onClick={()=>void remove(item)} className="inline-flex h-9 items-center justify-center gap-1.5 rounded-input border border-border-default text-xs font-medium text-text-secondary hover:text-danger"><Trash/>حذف</button></div>}</div>)}</div></section>)}</div>}</Card>;
}