import type { Locale } from '@/lib/i18n/locales';
import type {
  StatsSectionConfig, ServicesSectionConfig, FaqSectionConfig, CtaSectionConfig,
  PromoBannerSectionConfig, FreeContentSectionConfig, GallerySectionConfig, VideoSectionConfig,
  PropertyRequestSectionConfig,
} from '@sbaah/shared';

const copy = { ar: { request: 'أرسل طلبك', name: 'الاسم', phone: 'رقم الجوال', details: 'تفاصيل العقار المطلوب' }, en: { request: 'Send request', name: 'Name', phone: 'Phone', details: 'Property requirements' } };
const Shell=({children,className=''}:{children:React.ReactNode;className?:string})=><section className={`mx-auto w-full max-w-6xl px-6 py-12 sm:py-16 ${className}`}>{children}</section>;
const Heading=({children}:{children?:string})=>children?<h2 className="mb-7 border-s-4 border-tenant-secondary ps-3 text-2xl font-bold sm:text-3xl">{children}</h2>:null;

export function StatsSection({config}:{locale:Locale;config:StatsSectionConfig}){return <Shell><Heading>{config.title_ar||'أرقامنا'}</Heading><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{(config.items??[]).map((x,i)=><div key={i} className="rounded-2xl border border-black/10 p-5 text-center"><strong className="block text-2xl text-tenant-primary sm:text-3xl">{x.value}</strong><span className="mt-1 block text-sm text-black/60">{x.label}</span></div>)}</div></Shell>}
export function ServicesSection({config}:{locale:Locale;config:ServicesSectionConfig}){return <Shell><Heading>{config.title_ar||'خدماتنا'}</Heading><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(config.items??[]).map((x,i)=><article key={i} className="rounded-2xl border border-black/10 p-5"><span className="mb-4 block h-1 w-10 rounded-full bg-tenant-secondary"/><h3 className="font-bold">{x.title}</h3>{x.description&&<p className="mt-2 text-sm leading-7 text-black/60">{x.description}</p>}</article>)}</div></Shell>}
export function FaqSection({config}:{locale:Locale;config:FaqSectionConfig}){return <Shell className="max-w-4xl"><Heading>{config.title_ar||'الأسئلة الشائعة'}</Heading><div className="divide-y divide-black/10 border-y border-black/10">{(config.items??[]).map((x,i)=><details key={i} className="group py-4"><summary className="cursor-pointer list-none font-semibold">{x.question}</summary><p className="pt-3 text-sm leading-7 text-black/60">{x.answer}</p></details>)}</div></Shell>}
export function CtaSection({config}:{locale:Locale;config:CtaSectionConfig}){return <Shell><div className="flex flex-col gap-5 rounded-3xl bg-tenant-primary p-7 text-white sm:flex-row sm:items-center sm:justify-between sm:p-10"><div><h2 className="text-2xl font-bold">{config.title_ar}</h2>{config.body_ar&&<p className="mt-2 max-w-2xl text-sm text-white/80">{config.body_ar}</p>}</div>{config.button_label&&config.button_url&&<a href={config.button_url} className="w-fit rounded-xl bg-tenant-secondary px-5 py-3 text-sm font-semibold text-white">{config.button_label}</a>}</div></Shell>}
export function PromoBannerSection({config}:{locale:Locale;config:PromoBannerSectionConfig}){return <Shell><div className="relative overflow-hidden rounded-3xl bg-black/5 p-7 sm:p-10">{config.image_url&&<img src={config.image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-20"/>}<div className="relative max-w-2xl"><Heading>{config.title_ar}</Heading>{config.body_ar&&<p className="text-black/65">{config.body_ar}</p>}{config.button_label&&config.button_url&&<a href={config.button_url} className="mt-5 inline-block rounded-xl bg-tenant-primary px-5 py-3 text-sm font-semibold text-white">{config.button_label}</a>}</div></div></Shell>}
export function FreeContentSection({config}:{locale:Locale;config:FreeContentSectionConfig}){return <Shell><div className="grid items-center gap-7 sm:grid-cols-2">{config.image_url&&<img src={config.image_url} alt="" className="aspect-[4/3] w-full rounded-3xl object-cover"/>}<div><Heading>{config.title_ar}</Heading>{config.body_ar&&<p className="whitespace-pre-line leading-8 text-black/65">{config.body_ar}</p>}{config.button_label&&config.button_url&&<a href={config.button_url} className="mt-5 inline-block rounded-xl bg-tenant-primary px-5 py-3 text-sm font-semibold text-white">{config.button_label}</a>}</div></div></Shell>}
export function GallerySection({config}:{locale:Locale;config:GallerySectionConfig}){return <Shell><Heading>{config.title_ar||'معرض الصور'}</Heading><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{(config.image_urls??[]).map((url,i)=><img key={i} src={url} alt="" className="aspect-[4/3] w-full rounded-2xl object-cover"/>)}</div></Shell>}
export function VideoSection({config}:{locale:Locale;config:VideoSectionConfig}){return <Shell><Heading>{config.title_ar||'فيديو'}</Heading>{config.video_url&&<video controls preload="metadata" className="aspect-video w-full rounded-3xl bg-black" src={config.video_url}/>}</Shell>}
export function PropertyRequestSection({locale,config}:{locale:Locale;config:PropertyRequestSectionConfig}){const t=copy[locale];return <Shell className="max-w-4xl"><Heading>{config.title_ar||t.request}</Heading>{config.body_ar&&<p className="mb-5 text-black/60">{config.body_ar}</p>}<div className="grid gap-3 sm:grid-cols-2"><input disabled placeholder={t.name} className="h-12 rounded-xl border border-black/10 px-4"/><input disabled placeholder={t.phone} className="h-12 rounded-xl border border-black/10 px-4"/><textarea disabled placeholder={t.details} className="min-h-28 rounded-xl border border-black/10 p-4 sm:col-span-2"/><button disabled className="h-12 rounded-xl bg-tenant-primary px-5 font-semibold text-white opacity-70 sm:w-fit">{t.request}</button></div></Shell>}
