import type { City, FeaturedPropertiesSectionConfig, LatestPropertiesSectionConfig, ProjectsShowcaseSectionConfig, PropertiesByCitySectionConfig } from '@sbaah/shared';
import type { Locale } from '@/lib/i18n/locales';
import { listPublicProperties } from '@/lib/api/public-properties';
import { listPublicProjects } from '@/lib/api/public-projects';
import { listCities } from '@/lib/api/reference-data';
import { PropertyCard } from '@/components/properties/property-card';
import { ProjectCard } from '@/components/properties/project-card';
import { pickLocalized } from '@/lib/i18n/localized-field';
import { localizedPath } from '@/lib/routing/public-url';
const Shell=({children}:{children:React.ReactNode})=><section className="mx-auto w-full max-w-6xl px-6 py-12 sm:py-16">{children}</section>;
const Heading=({children}:{children:string})=><h2 className="mb-7 border-s-4 border-tenant-secondary ps-3 text-2xl font-bold sm:text-3xl">{children}</h2>;
export async function FeaturedPropertiesSection({locale,config}:{locale:Locale;config:FeaturedPropertiesSectionConfig}){const [r,cities]=await Promise.all([listPublicProperties({}),listCities()]);const ids=new Set(config.property_ids??[]);const items=(ids.size?r.properties.filter(p=>ids.has(p.id)):r.properties).slice(0,6);const m=new Map(cities.map(c=>[c.id,c]));return <Shell><Heading>{config.title_ar||'العقارات المميزة'}</Heading><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map(p=><PropertyCard key={p.id} property={p} city={m.get(p.city_id)} locale={locale}/>)}</div></Shell>}
export async function LatestPropertiesSection({locale,config}:{locale:Locale;config:LatestPropertiesSectionConfig}){const [r,cities]=await Promise.all([listPublicProperties({}),listCities()]);const m=new Map(cities.map(c=>[c.id,c]));return <Shell><Heading>{config.title_ar||'أحدث العقارات'}</Heading><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{r.properties.slice(0,Math.min(config.limit??6,12)).map(p=><PropertyCard key={p.id} property={p} city={m.get(p.city_id)} locale={locale}/>)}</div></Shell>}
export async function ProjectsShowcaseSection({locale,config}:{locale:Locale;config:ProjectsShowcaseSectionConfig}){const [r,cities]=await Promise.all([listPublicProjects(),listCities()]);const m=new Map(cities.map(c=>[c.id,c]));return <Shell><Heading>{config.title_ar||'المشاريع العقارية'}</Heading><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{r.projects.slice(0,Math.min(config.limit??6,12)).map(p=><ProjectCard key={p.id} project={p} city={m.get(p.city_id)} locale={locale}/>)}</div></Shell>}
export async function PropertiesByCitySection({locale,config}:{locale:Locale;config:PropertiesByCitySectionConfig}){const cities=await listCities();const selected=(config.city_ids?.length?cities.filter(c=>config.city_ids!.includes(c.id)):cities).slice(0,8);return <Shell><Heading>{config.title_ar||'العقارات حسب المدينة'}</Heading><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{selected.map((city:City)=><a key={city.id} href={`${localizedPath(locale,'/properties')}?city_id=${city.id}`} className="rounded-2xl border border-black/10 p-5 text-center font-semibold transition hover:border-tenant-secondary">{pickLocalized(locale,city.name_ar,city.name_en)}</a>)}</div></Shell>}
