'use client';
import { useEffect,useState } from 'react';
import { AppShell } from '@/components/layout/app-shell';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { useCurrentUser } from '@/lib/auth/current-user-context';
import { createSupportTicket,getSupportTicket,listSupportTickets,replySupportTicket,type SupportTicket } from '@/lib/api/support';

const statusLabel:Record<string,string>={open:'مفتوحة',in_progress:'قيد المعالجة',waiting_customer:'بانتظار ردك',resolved:'تم الحل',closed:'مغلقة'};
const typeLabel:Record<string,string>={complaint:'شكوى',suggestion:'اقتراح',support:'طلب دعم'};
const categoryLabel:Record<string,string>={billing:'الفوترة والاشتراك',technical:'تقنية',account:'الحساب',website:'الموقع الإلكتروني',domain:'الدومين',other:'أخرى'};

export default function SupportPage(){
 const {me,accessToken}=useCurrentUser(); const [tickets,setTickets]=useState<SupportTicket[]>([]); const [selected,setSelected]=useState<SupportTicket|null>(null); const [creating,setCreating]=useState(false); const [reply,setReply]=useState(''); const [form,setForm]=useState({type:'support',category:'technical',subject:'',description:''});
 const refresh=()=>void listSupportTickets(accessToken).then(r=>setTickets(r.tickets)); useEffect(refresh,[accessToken]);
 async function open(t:SupportTicket){const r=await getSupportTicket(accessToken,t.id);setSelected(r.ticket)}
 async function submit(e:React.FormEvent){e.preventDefault();const r=await createSupportTicket(accessToken,form);setCreating(false);setForm({type:'support',category:'technical',subject:'',description:''});refresh();await open(r.ticket)}
 async function send(){if(!selected||!reply.trim())return;await replySupportTicket(accessToken,selected.id,reply.trim());setReply('');await open(selected)}
 return <AppShell title="مركز الدعم" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><div className="flex flex-col gap-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-text-primary">التذاكر والدعم</h2><p className="text-sm text-text-secondary">ارفع شكوى أو اقتراحًا أو طلب دعم وتابع الردود من هنا.</p></div><Button onClick={()=>setCreating(v=>!v)}>{creating?'إلغاء':'تذكرة جديدة'}</Button></div>
  {creating&&<Card className="p-5"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="support">طلب دعم</option><option value="complaint">شكوى</option><option value="suggestion">اقتراح</option></Select><Select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{Object.entries(categoryLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><div className="md:col-span-2"><Input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="عنوان التذكرة" required /></div><textarea className="border-border-default bg-surface-card text-text-primary min-h-32 rounded-[14px] border p-3 text-sm outline-none md:col-span-2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="اشرح طلبك بالتفصيل..." required/><div className="md:col-span-2"><Button type="submit">إرسال التذكرة</Button></div></form></Card>}
  <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(340px,.8fr)]"><Card className="overflow-hidden"><div className="divide-y divide-border-subtle">{tickets.length===0?<p className="p-6 text-center text-sm text-text-secondary">لا توجد تذاكر حتى الآن.</p>:tickets.map(t=><button key={t.id} onClick={()=>void open(t)} className="hover:bg-surface-subtle flex w-full items-center justify-between gap-4 p-4 text-start"><div className="min-w-0"><div className="truncate font-semibold text-text-primary">{t.subject}</div><div className="mt-1 text-xs text-text-secondary" dir="ltr">{t.ticket_number}</div></div><div className="text-end"><div className="text-xs font-semibold text-brand">{statusLabel[t.status]??t.status}</div><div className="mt-1 text-[11px] text-text-placeholder">{typeLabel[t.type]} · {categoryLabel[t.category]}</div></div></button>)}</div></Card>
  <Card className="min-h-64 p-5">{selected?<div className="flex h-full flex-col"><div className="border-b border-border-subtle pb-4"><div className="flex items-start justify-between gap-3"><h3 className="font-bold text-text-primary">{selected.subject}</h3><span className="rounded-full bg-brand-surface px-3 py-1 text-xs font-semibold text-brand">{statusLabel[selected.status]}</span></div><p className="mt-2 text-xs text-text-secondary" dir="ltr">{selected.ticket_number}</p><p className="mt-3 whitespace-pre-wrap text-sm text-text-secondary">{selected.description}</p></div><div className="flex flex-1 flex-col gap-3 py-4">{selected.support_ticket_messages?.map((m,i)=><div key={m.id??i} className={`max-w-[88%] rounded-2xl p-3 text-sm ${m.sender_type==='admin'?'bg-brand-surface text-text-primary':'ms-auto bg-surface-subtle text-text-primary'}`}><div className="mb-1 text-[11px] font-semibold text-text-secondary">{m.sender_type==='admin'?'فريق دعم سبعة':'أنت'}</div>{m.message}</div>)}</div>{!['closed'].includes(selected.status)&&<div className="flex gap-2"><Input value={reply} onChange={e=>setReply(e.target.value)} placeholder="اكتب ردك..." /><Button onClick={()=>void send()}>إرسال</Button></div>}</div>:<div className="flex h-full min-h-52 items-center justify-center text-sm text-text-secondary">اختر تذكرة لعرض المحادثة ومتابعتها.</div>}</Card></div>
 </div></AppShell>
}
