import type { Locale } from '@/lib/i18n/locales';
import type { StatsSectionConfig,ServicesSectionConfig,FaqSectionConfig,CtaSectionConfig,PromoBannerSectionConfig,FreeContentSectionConfig,GallerySectionConfig,VideoSectionConfig } from '@sbaah/shared';
import {LavenderHeading,LavenderSection} from './primitives';
const copy={ar:{stats:'أرقامنا',services:'خدماتنا',faq:'الأسئلة الشائعة',gallery:'معرض الصور',video:'فيديو'},en:{stats:'Our numbers',services:'Services',faq:'Frequently asked questions',gallery:'Gallery',video:'Video'}} as const;
function href(v?:string){if(!v)return null;const x=v.trim();return /^(\/|https?:\/\/|tel:|mailto:)/.test(x)?x:null}
function Action({label,url,light=false}:{label?:string;url?:string;light?:boolean}){const h=href(url);return label&&h?<a href={h} className={`inline-block border-b pb-1 text-sm font-semibold ${light?'border-white/60 text-white':'border-black/50 text-black'}`}>{label} ↗</a>:null}

export function LavenderStats({locale,config}:{locale:Locale;config:StatsSectionConfig}){const items=(config.items??[]).filter(i=>i.value||i.label);return <LavenderSection className="bg-[#171713] text-white"><div className="mb-12 border-b border-white/20 pb-5"><h2 className="text-3xl font-medium sm:text-5xl">{config.title_ar||copy[locale].stats}</h2></div><div className="grid border-t border-white/20 sm:grid-cols-2 lg:grid-cols-4">{items.map((i,n)=><div key={n} className="border-b border-white/20 py-7 sm:border-e sm:px-6 sm:first:ps-0"><strong className="block text-5xl font-light tracking-tight sm:text-6xl">{i.value}</strong><span className="mt-4 block text-sm text-white/50">{i.label}</span></div>)}</div></LavenderSection>}
export function LavenderServices({locale,config}:{locale:Locale;config:ServicesSectionConfig}){const items=(config.items??[]).filter(i=>i.title);return <LavenderSection><LavenderHeading eyebrow={locale==='ar'?'ما نقدمه':'What we do'} title={config.title_ar||copy[locale].services}/><div className="border-t border-black/20">{items.map((i,n)=><article key={n} className="grid gap-3 border-b border-black/20 py-6 sm:grid-cols-[4rem_.65fr_1fr] sm:items-start sm:py-8"><span className="text-xs text-black/35">{String(n+1).padStart(2,'0')}</span><h3 className="text-xl font-medium sm:text-2xl">{i.title}</h3>{i.description&&<p className="max-w-2xl text-sm leading-7 text-black/55">{i.description}</p>}</article>)}</div></LavenderSection>}
export function LavenderFaq({locale,config}:{locale:Locale;config:FaqSectionConfig}){const items=(config.items??[]).filter(i=>i.question&&i.answer);return <LavenderSection className="bg-[#f4f1ea]"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><h2 className="text-3xl font-medium sm:text-5xl">{config.title_ar||copy[locale].faq}</h2><div className="border-t border-black/20">{items.map((i,n)=><details key={n} className="group border-b border-black/20"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 text-lg font-medium"><span>{i.question}</span><span className="text-2xl font-light group-open:rotate-45">+</span></summary><p className="max-w-2xl pb-7 text-sm leading-7 text-black/55">{i.answer}</p></details>)}</div></div></LavenderSection>}
export function LavenderCta({config}:{locale:Locale;config:CtaSectionConfig}){if(!config.title_ar&&!config.body_ar)return null;return <section className="bg-tenant-primary px-5 py-16 text-white sm:px-6 sm:py-24"><div className="mx-auto grid max-w-7xl gap-8 border-t border-white/40 pt-7 lg:grid-cols-[1.3fr_.7fr]"><h2 className="text-4xl font-medium leading-tight sm:text-6xl">{config.title_ar}</h2><div className="lg:pt-2">{config.body_ar&&<p className="mb-7 max-w-xl leading-8 text-white/70">{config.body_ar}</p>}<Action label={config.button_label} url={config.button_url} light/></div></div></section>}
export function LavenderPromo({config}:{locale:Locale;config:PromoBannerSectionConfig}){if(!config.title_ar&&!config.image_url)return null;return <section className="relative min-h-[65vh] overflow-hidden bg-[#171713] text-white">{config.image_url&&<img src={config.image_url} alt="" className="absolute inset-0 h-full w-full object-cover"/>}<div className="absolute inset-0 bg-black/45"/><div className="relative mx-auto flex min-h-[65vh] max-w-7xl flex-col justify-end px-5 py-12 sm:px-6 sm:py-16"><div className="max-w-3xl border-t border-white/45 pt-6"><h2 className="text-4xl font-medium sm:text-6xl">{config.title_ar}</h2>{config.body_ar&&<p className="mt-4 max-w-xl leading-8 text-white/70">{config.body_ar}</p>}<div className="mt-6"><Action label={config.button_label} url={config.button_url} light/></div></div></div></section>}
export function LavenderFreeContent({config}:{locale:Locale;config:FreeContentSectionConfig}){if(!config.title_ar&&!config.body_ar&&!config.image_url)return null;return <LavenderSection><div className="grid gap-8 lg:grid-cols-2 lg:gap-16">{config.image_url&&<img src={config.image_url} alt="" className="aspect-[4/3] h-full w-full object-cover"/>}<div className="flex flex-col justify-center border-t border-black/20 pt-6"><h2 className="text-3xl font-medium leading-tight sm:text-5xl">{config.title_ar}</h2>{config.body_ar&&<p className="mt-6 whitespace-pre-line leading-8 text-black/55">{config.body_ar}</p>}<div className="mt-8"><Action label={config.button_label} url={config.button_url}/></div></div></div></LavenderSection>}
export function LavenderGallery({locale,config}:{locale:Locale;config:GallerySectionConfig}){const imgs=(config.image_urls??[]).filter(Boolean);return <LavenderSection className="bg-[#171713] text-white"><div className="mb-10 border-b border-white/20 pb-5"><h2 className="text-3xl font-medium sm:text-5xl">{config.title_ar||copy[locale].gallery}</h2></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{imgs.map((u,n)=><div key={u+n} className={n===0?'col-span-2 row-span-2':''}><img src={u} alt="" loading="lazy" className="aspect-[4/3] h-full w-full object-cover"/></div>)}</div></LavenderSection>}
export function LavenderVideo({locale,config}:{locale:Locale;config:VideoSectionConfig}){if(!config.video_url)return null;return <LavenderSection><LavenderHeading eyebrow={locale==='ar'?'شاهد':'Watch'} title={config.title_ar||copy[locale].video}/><video controls playsInline preload="metadata" className="aspect-video w-full bg-black" src={config.video_url}/></LavenderSection>}
