import type { Locale } from '@/lib/i18n/locales';
import type { PublicProjectDetailResponse } from '@/lib/api/public-projects';
import { pickLocalized } from '@/lib/i18n/localized-field';
import { localizedPath } from '@/lib/routing/public-url';
import Link from 'next/link';

const labels:Record<string,{ar:string;en:string}>={bedrooms:{ar:'غرف النوم',en:'Bedrooms'},bathrooms:{ar:'دورات المياه',en:'Bathrooms'},area_sqm:{ar:'المساحة',en:'Area'},base_price:{ar:'السعر يبدأ من',en:'Starting price'},floors:{ar:'الأدوار',en:'Floors'},parking:{ar:'مواقف',en:'Parking'}};
const specLabel=(k:string,l:Locale)=>labels[k]?.[l]??k.replaceAll('_',' ');

export function LavenderProjectDetail({locale,data}:{locale:Locale;data:PublicProjectDetailResponse}){
 const p=data.project,title=pickLocalized(locale,p.name_ar,p.name_en),desc=pickLocalized(locale,p.description_ar??'',p.description_en??null);
 const images=data.media.filter(m=>m.media_type==='image'),primary=images.find(m=>m.is_primary)??images[0],by=(x:string)=>images.filter(m=>m.category===x);
 const gallery=images.filter(m=>['general','exterior','interior'].includes(m.category)).slice(0,6);
 const sections=[['master_plan',locale==='ar'?'مخطط المشروع':'Master plan'],['unit_plans',locale==='ar'?'مخططات الوحدات':'Unit plans'],['amenities',locale==='ar'?'المرافق والخدمات':'Amenities'],['location',locale==='ar'?'الموقع والمحيط':'Location'],['construction',locale==='ar'?'مراحل الإنشاء':'Construction progress']] as const;
 const money=(n:number)=>new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA',{maximumFractionDigits:0}).format(n);
 return <main className="bg-[#f4f1ea] text-[#171713]">
  <section className="relative min-h-[68svh] overflow-hidden bg-[#171713] text-white sm:min-h-[78vh]">{primary&&<img src={primary.url} alt={title} className="absolute inset-0 h-full w-full object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-black/20"/><div className="relative mx-auto flex min-h-[68svh] max-w-7xl items-end px-4 pb-8 pt-28 sm:min-h-[78vh] sm:px-6 sm:pb-14"><div className="w-full max-w-4xl"><p className="mb-3 text-[10px] font-semibold tracking-[.18em] text-white/65">{locale==='ar'?'مشروع عقاري':'REAL ESTATE PROJECT'}</p><h1 className="text-4xl font-medium leading-[1.08] sm:text-6xl lg:text-7xl">{title}</h1><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 border-t border-white/30 pt-4 text-xs text-white/75">{typeof p.completion_percentage==='number'&&<span>{locale==='ar'?'الإنجاز':'Progress'} <b className="text-white">{p.completion_percentage}%</b></span>}{p.planned_units_count!=null&&<span>{locale==='ar'?'الوحدات':'Units'} <b className="text-white">{String(p.planned_units_count)}</b></span>}<span>{locale==='ar'?'النماذج':'Models'} <b className="text-white">{data.unit_types.length}</b></span></div></div></div></section>
  <nav className="sticky top-0 z-20 overflow-x-auto border-b border-black/10 bg-[#f4f1ea]/95 px-4 backdrop-blur sm:px-6"><div className="mx-auto flex max-w-7xl min-w-max gap-6 py-4 text-xs font-medium"><a href="#about">{locale==='ar'?'عن المشروع':'About'}</a>{data.unit_types.length>0&&<a href="#models">{locale==='ar'?'النماذج':'Models'}</a>}{data.units.length>0&&<a href="#units">{locale==='ar'?'الوحدات':'Units'}</a>}{by('location').length>0&&<a href="#location">{locale==='ar'?'الموقع':'Location'}</a>}</div></nav>
  <section id="about" className="px-4 py-12 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl lg:grid lg:grid-cols-[.65fr_1.35fr] lg:gap-16"><h2 className="mb-6 text-3xl font-medium sm:text-5xl">{locale==='ar'?'عن المشروع':'About'}</h2><div>{desc&&<p className="max-w-3xl whitespace-pre-line text-base leading-8 text-black/60 sm:text-lg sm:leading-9">{desc}</p>}<div className="mt-8 grid grid-cols-2 gap-px border border-black/10 bg-black/10 sm:grid-cols-3">{typeof p.completion_percentage==='number'&&<div className="bg-[#f4f1ea] p-4 sm:p-6"><span className="text-xs text-black/45">{locale==='ar'?'نسبة الإنجاز':'Progress'}</span><strong className="mt-2 block text-2xl sm:text-3xl">{p.completion_percentage}%</strong></div>}{p.planned_units_count!=null&&<div className="bg-[#f4f1ea] p-4 sm:p-6"><span className="text-xs text-black/45">{locale==='ar'?'عدد الوحدات':'Units'}</span><strong className="mt-2 block text-2xl sm:text-3xl">{String(p.planned_units_count)}</strong></div>}<div className="bg-[#f4f1ea] p-4 sm:p-6"><span className="text-xs text-black/45">{locale==='ar'?'نماذج المشروع':'Models'}</span><strong className="mt-2 block text-2xl sm:text-3xl">{data.unit_types.length}</strong></div></div></div></div></section>
  {gallery.length>0&&<section className="px-4 pb-12 sm:px-6 sm:pb-20"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-1 sm:grid-cols-12">{gallery.map((m,i)=><img key={m.id} src={m.url} alt={pickLocalized(locale,m.alt_ar??title,m.alt_en)} className={(i===0?'col-span-2 aspect-[16/10] sm:col-span-8 sm:row-span-2 ':'aspect-square sm:col-span-4 ')+'h-full w-full object-cover'}/>)}</div></section>}
  {data.unit_types.length>0&&<section id="models" className="bg-white px-4 py-12 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><div className="mb-7 flex items-end justify-between border-b border-black/15 pb-4"><h2 className="text-3xl font-medium sm:text-5xl">{locale==='ar'?'نماذج المشروع':'Project models'}</h2><span className="text-xs text-black/40">{data.unit_types.length}</span></div><div className="divide-y divide-black/10">{data.unit_types.map((t,i)=>{const facts=[['area_sqm',t.area_sqm],['bedrooms',t.bedrooms],['bathrooms',t.bathrooms],['base_price',t.base_price],...Object.entries(t.specifications??{})].filter(([,v])=>v!==null&&v!==undefined&&v!=='').slice(0,6);return <article key={t.id} className="py-6 sm:grid sm:grid-cols-[3rem_.7fr_1.3fr] sm:gap-6"><div className="mb-2 text-[10px] text-black/35 sm:mb-0">{String(i+1).padStart(2,'0')}</div><h3 className="mb-4 text-2xl font-medium sm:mb-0">{pickLocalized(locale,t.name_ar,t.name_en)}</h3><dl className="grid grid-cols-2 gap-x-5 gap-y-3 text-xs">{facts.map(([k,v])=><div key={k} className="border-b border-black/10 pb-2"><dt className="text-black/40">{specLabel(k,locale)}</dt><dd className="mt-1 font-medium">{k==='base_price'&&typeof v==='number'?money(v)+' '+(locale==='ar'?'ر.س':'SAR'):k==='area_sqm'?String(v)+' m²':String(v)}</dd></div>)}</dl></article>})}</div></div></section>}
  {sections.map(([key,label])=>{const items=by(key);if(!items.length)return null;return <section id={key==='location'?'location':undefined} key={key} className="px-4 py-12 sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-end justify-between border-b border-black/15 pb-4"><h2 className="text-3xl font-medium sm:text-5xl">{label}</h2><span className="text-xs text-black/40">{items.length}</span></div><div className={key==='master_plan'?'grid gap-2':'grid grid-cols-2 gap-1 sm:grid-cols-3'}>{items.map(m=><img key={m.id} src={m.url} alt={pickLocalized(locale,m.alt_ar??label,m.alt_en)} className={key==='master_plan'?'max-h-[760px] w-full bg-white object-contain':'aspect-[4/3] h-full w-full object-cover'}/>)}</div></div></section>})}
  {data.units.length>0&&<section id="units" className="bg-[#171713] px-4 py-12 text-white sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-end justify-between border-b border-white/20 pb-4"><h2 className="text-3xl font-medium sm:text-5xl">{locale==='ar'?'الوحدات المتاحة':'Available units'}</h2><span className="text-xs text-white/50">{data.units.length}</span></div><div className="divide-y divide-white/15">{data.units.map(u=><Link key={u.id} href={localizedPath(locale,'/properties/'+(u.slug??u.id))} className="grid grid-cols-[1fr_auto] items-center gap-4 py-5 sm:grid-cols-[1fr_.5fr_.5fr_auto]"><div><strong className="block text-sm sm:text-base">{u.name_ar||u.unit_number||u.listing_number}</strong>{u.area_sqm&&<span className="mt-1 block text-xs text-white/50 sm:hidden">{u.area_sqm} m²</span>}</div><span className="hidden text-sm text-white/55 sm:block">{u.area_sqm?u.area_sqm+' m²':''}</span><span className="hidden text-sm text-white/55 sm:block">{u.listing_type}</span><span className="whitespace-nowrap text-sm">{u.price!=null?money(u.price)+' '+(locale==='ar'?'ر.س':'SAR'):''} ↗</span></Link>)}</div></div></section>}
  {data.media.some(m=>m.media_type==='video')&&<section className="bg-black px-4 py-12 text-white sm:px-6 sm:py-20"><div className="mx-auto max-w-7xl"><h2 className="mb-6 text-3xl font-medium sm:text-5xl">{locale==='ar'?'فيديو المشروع':'Project video'}</h2>{data.media.filter(m=>m.media_type==='video').slice(0,1).map(m=><video key={m.id} src={m.url} controls playsInline className="aspect-video w-full"/>)}</div></section>}
 </main>
}