import type { Locale } from '@/lib/i18n/locales';
import type { PublicProjectDetailResponse } from '@/lib/api/public-projects';
import { pickLocalized } from '@/lib/i18n/localized-field';
import { localizedPath } from '@/lib/routing/public-url';
import Link from 'next/link';

export function LavenderProjectDetail({locale,data}:{locale:Locale;data:PublicProjectDetailResponse}){
 const p=data.project; const title=pickLocalized(locale,p.name_ar,p.name_en); const desc=pickLocalized(locale,p.description_ar??'',p.description_en??null);
 const images=data.media.filter(m=>m.media_type==='image'); const primary=images.find(m=>m.is_primary)??images[0]; const by=(x:string)=>images.filter(m=>m.category===x);
 const groups=new Map<string,typeof data.units>(); for(const u of data.units){const k=u.floor_number==null?(locale==='ar'?'وحدات أخرى':'Other units'):(locale==='ar'?'الدور '+u.floor_number:'Floor '+u.floor_number);groups.set(k,[...(groups.get(k)??[]),u])}
 const sections=[['master_plan',locale==='ar'?'مخطط المشروع':'Master plan'],['unit_plans',locale==='ar'?'مخططات الوحدات':'Unit plans'],['amenities',locale==='ar'?'المرافق والخدمات':'Amenities'],['location',locale==='ar'?'الموقع والمحيط':'Location'],['construction',locale==='ar'?'مراحل الإنشاء':'Construction progress']] as const;
 return <div className="bg-[#f4f1ea] text-black">
 <section className="relative -mt-24 min-h-[82vh] overflow-hidden bg-[#171713] text-white">{primary&&<img src={primary.url} alt={title} className="absolute inset-0 h-full w-full object-cover"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/15 to-black/35"/><div className="relative mx-auto flex min-h-[82vh] max-w-7xl items-end px-5 pb-12 pt-40 sm:px-6 sm:pb-16"><div className="w-full border-t border-white/40 pt-6"><p className="mb-3 text-xs uppercase tracking-[.18em] text-white/60">{locale==='ar'?'مشروع عقاري':'Real estate project'}</p><h1 className="max-w-5xl text-5xl font-medium leading-none sm:text-7xl">{title}</h1></div></div></section>
 <section className="px-5 py-16 sm:px-6 sm:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><h2 className="text-3xl font-medium sm:text-5xl">{locale==='ar'?'عن المشروع':'About the project'}</h2><div>{desc&&<p className="max-w-3xl whitespace-pre-line text-lg leading-9 text-black/60">{desc}</p>}<dl className="mt-10 grid grid-cols-2 border-t border-black/20">{typeof p.completion_percentage==='number'&&<div className="border-b border-black/20 py-5"><dt className="text-xs text-black/45">{locale==='ar'?'نسبة الإنجاز':'Completion'}</dt><dd className="mt-2 text-3xl">{String(p.completion_percentage)}%</dd></div>}{p.planned_units_count!=null&&<div className="border-b border-black/20 py-5"><dt className="text-xs text-black/45">{locale==='ar'?'عدد الوحدات':'Units'}</dt><dd className="mt-2 text-3xl">{String(p.planned_units_count)}</dd></div>}</dl></div></div></section>
 {data.unit_types.length>0&&<section className="bg-white px-5 py-16 sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><h2 className="mb-10 border-b border-black/20 pb-5 text-3xl font-medium sm:text-5xl">{locale==='ar'?'نماذج المشروع':'Project models'}</h2><div className="border-t border-black/20">{data.unit_types.map((t,i)=><article key={t.id} className="grid gap-5 border-b border-black/20 py-7 sm:grid-cols-[4rem_.7fr_1.3fr]"><span className="text-xs text-black/35">{String(i+1).padStart(2,'0')}</span><h3 className="text-2xl font-medium">{pickLocalized(locale,t.name_ar,t.name_en)}</h3><div className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">{Object.entries(t.specifications??{}).slice(0,8).map(([k,v])=><div key={k} className="border-b border-black/10 pb-2"><span className="text-black/35">{k}</span><span className="float-end">{String(v)}</span></div>)}</div></article>)}</div></div></section>}
 {sections.map(([key,label])=>{const items=by(key);return items.length?<section key={key} className="px-5 py-16 sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><div className="mb-8 flex items-end justify-between border-b border-black/20 pb-5"><h2 className="text-3xl font-medium sm:text-5xl">{label}</h2><span className="text-xs text-black/40">{items.length}</span></div><div className={key==='master_plan'?'grid':'grid grid-cols-2 gap-2 sm:grid-cols-3'}>{items.map(m=><img key={m.id} src={m.url} alt={pickLocalized(locale,m.alt_ar??label,m.alt_en)} className={key==='master_plan'?'max-h-[800px] w-full object-contain':'aspect-[4/3] h-full w-full object-cover'}/>)}</div></div></section>:null})}
 
 {groups.size>0&&<section className="bg-[#171713] px-5 py-16 text-white sm:px-6 sm:py-24"><div className="mx-auto max-w-7xl"><h2 className="mb-10 border-b border-white/20 pb-5 text-3xl font-medium sm:text-5xl">{locale==='ar'?'الوحدات المتاحة':'Available units'}</h2>{[...groups].map(([floor,units])=><div key={floor} className="mb-12"><h3 className="mb-5 text-xl text-white/60">{floor}</h3><div className="border-t border-white/20">{units.map(u=><Link key={u.id} href={localizedPath(locale,'/properties/'+(u.slug??u.id))} className="grid grid-cols-[1fr_auto] gap-4 border-b border-white/20 py-5 sm:grid-cols-[1fr_.5fr_.5fr_auto]"><strong>{u.name_ar||u.unit_number||u.listing_number}</strong><span className="hidden text-white/50 sm:block">{u.area_sqm?u.area_sqm+' m²':''}</span><span className="hidden text-white/50 sm:block">{u.listing_type}</span><span>{u.price!=null?new Intl.NumberFormat(locale==='ar'?'ar-SA':'en-SA').format(u.price)+' SAR':''} ↗</span></Link>)}</div></div>)}</div></section>}
 </div>
}