import Image from 'next/image';
import type { Locale } from '@/lib/i18n/locales';
import { Hero } from './marketing/hero';
import { HowItWorks } from './marketing/how-it-works';
import { ProductShowcase } from './marketing/product-showcase';
import { FeatureGrid } from './marketing/feature-grid';
import { Pricing } from './marketing/pricing';
import { Faq } from './marketing/faq';
import { FinalCta } from './marketing/final-cta';

function ProblemSection({ locale }: { locale: Locale }) {
  const ar = locale === 'ar';
  const items = ar ? [['موقعك', 'اعرض عقاراتك ومشاريعك بهويتك.'], ['عملاؤك', 'بيانات وطلبات مرتبة وواضحة.'], ['متابعتك', 'كل فرصة في مسار واحد.']] : [['Your website', 'Show properties and projects under your brand.'], ['Your clients', 'Organized client data and requests.'], ['Your follow-up', 'Every opportunity in one clear flow.']];
  return <section className="bg-white px-5 py-14 sm:px-6 sm:py-18"><div className="mx-auto grid max-w-5xl items-center gap-10 lg:grid-cols-[.8fr_1.2fr]">
    <div><span className="text-brand text-xs font-bold sm:text-sm">{ar ? 'بدل الأدوات المتفرقة' : 'Instead of scattered tools'}</span><h2 className="text-text-primary mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{ar ? 'كل شغلك العقاري في مكان واحد' : 'Your real-estate work, in one place'}</h2><p className="text-text-secondary mt-3 text-sm leading-7 sm:text-base">{ar ? 'موقعك، عقاراتك، العملاء والطلبات؛ مرتبطة معًا داخل سبعة.' : 'Your website, properties, clients and requests — connected inside Sbaah.'}</p><div className="mt-7 space-y-4 border-t border-black/8 pt-5">{items.map(([title, body],index)=><div key={title} className="flex gap-4"><span className="text-brand text-xs font-bold">0{index+1}</span><div><h3 className="text-sm font-bold">{title}</h3><p className="text-text-secondary mt-0.5 text-sm">{body}</p></div></div>)}</div></div>
    <div className="relative min-h-[320px] overflow-hidden rounded-[2rem] bg-[#eee9f3] p-4 sm:min-h-[400px] sm:p-7"><div className="absolute -end-16 -top-16 h-52 w-52 rounded-full bg-brand/15 blur-3xl"/><div className="relative overflow-hidden rounded-2xl border border-black/5 bg-white shadow-xl"><div className="flex items-center justify-between border-b border-black/5 px-4 py-3"><div className="h-2.5 w-20 rounded bg-brand/15"/><div className="flex gap-1"><i className="h-2 w-2 rounded-full bg-neutral-200"/><i className="h-2 w-2 rounded-full bg-neutral-200"/></div></div><Image src="/marketing/dashboard-preview.webp" alt={ar?'لوحة تحكم سبعة':'Sbaah dashboard'} width={1600} height={1000} className="h-auto w-full"/></div><div className="absolute bottom-3 start-3 w-44 rounded-2xl border border-white/70 bg-white/95 p-4 shadow-xl backdrop-blur sm:bottom-6 sm:start-6 sm:w-52"><div className="text-brand text-[10px] font-bold">CRM</div><div className="mt-2 flex items-end gap-1.5">{[35,58,44,78,62,90].map((h,i)=><span key={i} className="bg-brand/70 flex-1 rounded-t" style={{height:`${h*.55}px`}}/>)}</div><p className="mt-2 text-[10px] text-text-secondary">{ar?'متابعة العملاء والفرص':'Clients & opportunities'}</p></div></div>
  </div></section>;
}

function WebsiteSection({ locale }: { locale: Locale }) {
  const ar=locale==='ar'; const bullets=ar?['ثيمات قابلة للتخصيص','عربي وإنجليزي','دومينك الخاص','متوافق مع الجوال']:['Customizable themes','Arabic & English','Your own domain','Mobile ready'];
  return <section className="bg-neutral-50 px-5 py-14 sm:px-6 sm:py-18"><div className="mx-auto max-w-5xl"><div className="max-w-2xl"><span className="text-brand text-xs font-bold sm:text-sm">{ar?'موقعك العقاري':'Your website'}</span><h2 className="text-text-primary mt-2 text-2xl font-bold tracking-tight sm:text-3xl">{ar?'موقع احترافي باسمك وهويتك':'A professional website under your brand'}</h2><p className="text-text-secondary mt-3 max-w-xl text-sm leading-7 sm:text-base">{ar?'اختر الثيم، أضف عقاراتك وانشر موقعك. بدون بناء تقني من الصفر.':'Choose a theme, add your properties and publish. No building from scratch.'}</p></div>
    <div className="relative mt-8 overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#e9e2f0] via-[#f7f4f9] to-white p-5 sm:p-9"><div className="grid items-end gap-5 md:grid-cols-[1fr_240px]"><div className="overflow-hidden rounded-2xl border border-black/5 bg-white shadow-xl"><div className="flex h-9 items-center gap-1.5 border-b px-3"><i className="h-2 w-2 rounded-full bg-neutral-300"/><i className="h-2 w-2 rounded-full bg-neutral-300"/><span className="ms-3 text-[9px] text-neutral-400">yourname.sbaah.app</span></div><div className="relative aspect-[16/8] overflow-hidden bg-[#182a36]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,rgba(104,69,138,.55),transparent_38%)]"/><div className="relative flex h-full flex-col justify-end p-6 text-white sm:p-9"><span className="text-[10px] text-white/70">{ar?'مشروع سكني • الرياض':'Residential project • Riyadh'}</span><strong className="mt-2 max-w-sm text-xl sm:text-3xl">{ar?'مساحات مصممة لحياة أفضل':'Spaces designed for better living'}</strong><div className="mt-4 h-8 w-24 rounded-lg bg-white/95"/></div></div></div><div className="mx-auto w-[190px] rounded-[2rem] border-[7px] border-neutral-900 bg-white p-1 shadow-2xl md:-mb-5"><div className="overflow-hidden rounded-[1.45rem] bg-white"><div className="aspect-[9/15] bg-gradient-to-b from-[#2b2033] via-[#5b456b] to-[#f5f2f7] p-3"><div className="h-2 w-10 rounded bg-white/80"/><div className="mt-20 rounded-xl bg-white p-2 shadow"><div className="h-20 rounded-lg bg-gradient-to-br from-[#c9c0cf] to-[#7d7184]"/><div className="mt-2 h-2 w-3/4 rounded bg-neutral-800"/><div className="mt-1 h-1.5 w-1/2 rounded bg-neutral-300"/></div></div></div></div></div></div>
    <div className="mt-6 flex flex-wrap gap-x-6 gap-y-3 border-b border-black/8 pb-7">{bullets.map(item=><div key={item} className="flex items-center gap-2 text-sm font-medium"><span className="bg-brand h-1.5 w-1.5 rounded-full"/>{item}</div>)}</div></div></section>;
}

function AudienceSection({locale}:{locale:Locale}) {const ar=locale==='ar';const audiences=ar?[['مطور عقاري','اعرض مشاريعك وتابع الفرص.'],['مسوّق عقاري','نظّم مخزونك وعملاءك.'],['وسيط عقاري','ابنِ حضورك وأدر طلباتك.']]:[['Developer','Show projects and track opportunities.'],['Marketer','Organize inventory and clients.'],['Broker','Build your presence and manage requests.']];return <section className="bg-white px-5 py-14 sm:px-6 sm:py-18"><div className="mx-auto max-w-5xl"><span className="text-brand text-xs font-bold sm:text-sm">{ar?'مصممة للعقار':'Built for real estate'}</span><h2 className="text-text-primary mt-2 text-2xl font-bold sm:text-3xl">{ar?'سبعة تناسب طريقة عملك':'Sbaah fits your workflow'}</h2><div className="mt-8 grid gap-4 sm:grid-cols-3">{audiences.map(([title,body],index)=><div key={title} className="group overflow-hidden rounded-2xl border border-black/7 bg-[#faf9fb]"><div className="relative h-28 overflow-hidden bg-gradient-to-br from-[#32263b] to-[#8a6aa0]"><div className={`absolute h-36 w-24 rounded-[45%] bg-white/12 ${index===0?'start-8 top-6 rotate-12':index===1?'end-7 top-5 -rotate-12':'start-1/2 top-7 -translate-x-1/2'}`}/><div className="absolute inset-x-4 bottom-4 flex gap-2"><span className="h-7 flex-1 rounded-lg bg-white/90"/><span className="h-7 w-9 rounded-lg bg-white/30"/></div></div><div className="p-5"><h3 className="text-base font-bold">{title}</h3><p className="text-text-secondary mt-1 text-sm leading-6">{body}</p></div></div>)}</div></div></section>}

const ecosystemNames=[{ar:'الهيئة العامة للعقار',en:'Real Estate General Authority',short:'REGA'},{ar:'فال',en:'FAL',short:'فال'},{ar:'السجل العقاري',en:'Real Estate Registry',short:'RER'},{ar:'إيجار',en:'Ejar',short:'إيجار'},{ar:'صندوق الاستثمارات العامة',en:'Public Investment Fund',short:'PIF'},{ar:'وزارة الاتصالات وتقنية المعلومات',en:'Ministry of Communications and Information Technology',short:'MCIT'}];
function EcosystemSection({locale}:{locale:Locale}) {const ar=locale==='ar';const Set=({copy}:{copy:number})=><div className="flex shrink-0 items-center gap-8 pe-8" aria-hidden={copy===2}>{ecosystemNames.map((item,index)=><div key={`${copy}-${index}`} className="flex h-12 shrink-0 items-center gap-2.5"><div className="text-brand text-[10px] font-bold">{item.short}</div><span className="text-start text-[11px] font-semibold">{ar?item.ar:item.en}</span></div>)}</div>;return <section className="overflow-hidden border-y border-brand/10 bg-[#faf9fb] py-6"><div className="px-5 text-center"><p className="text-brand text-xs font-bold">{ar?'ضمن المنظومة العقارية السعودية':'Saudi real-estate ecosystem'}</p></div><div className="relative mt-4 overflow-hidden"><div className="pointer-events-none absolute inset-y-0 left-0 z-10 w-12 bg-gradient-to-r from-[#faf9fb] to-transparent"/><div className="pointer-events-none absolute inset-y-0 right-0 z-10 w-12 bg-gradient-to-l from-[#faf9fb] to-transparent"/><div className="sbaah-ecosystem-marquee flex w-max" dir="ltr"><Set copy={1}/><Set copy={2}/></div></div><style>{`@keyframes sbaahEcosystemMarquee{from{transform:translate3d(0,0,0)}to{transform:translate3d(-50%,0,0)}}.sbaah-ecosystem-marquee{animation:sbaahEcosystemMarquee 32s linear infinite;will-change:transform}`}</style></section>}

export function MarketingHome({locale}:{locale:Locale}) {return <div><Hero locale={locale}/><ProblemSection locale={locale}/><ProductShowcase locale={locale}/><WebsiteSection locale={locale}/><FeatureGrid locale={locale}/><HowItWorks locale={locale}/><AudienceSection locale={locale}/><EcosystemSection locale={locale}/><Pricing locale={locale}/><Faq locale={locale}/><FinalCta locale={locale}/></div>}
