'use client';

import { use, useEffect, useState } from 'react';
import { isNotFoundError } from '@sbaah/shared';
import { AppShell } from '@/components/layout/app-shell';
import { BackButton } from '@/components/ui/back-button';
import { Card } from '@/components/ui/card';
import { DetailLoadError } from '@/components/ui/detail-load-error';
import { PersonAvatar } from '@/components/ui/person-avatar';
import { SegmentedToggle } from '@/components/ui/segmented-toggle';
import { FormPageSkeleton } from '@/components/ui/form-page-skeleton';
import { useCurrentUser } from '@/lib/auth/current-user-context';
import { getEjarTenant, type TenantRentalProfile } from '@/lib/api/rent-plus';

type Tab='info'|'contracts'|'payments'|'maintenance';
const money=(v:number)=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR',maximumFractionDigits:0}).format(v);
const date=(v:string)=>new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v));
const contractStatus:Record<string,string>={draft:'مسودة',upcoming:'قادم',active:'نشط',expired:'منتهي',terminated:'منهى',cancelled:'ملغي'};
const maintenanceStatus:Record<string,string>={open:'مفتوح',in_review:'قيد المراجعة',scheduled:'مجدول',in_progress:'قيد التنفيذ',completed:'مكتمل',cancelled:'ملغي'};

export default function TenantDetailPage({params}:{params:Promise<{id:string}>}){
  const{id}=use(params);const{me,accessToken}=useCurrentUser();const[data,setData]=useState<TenantRentalProfile|null>(null);const[notFound,setNotFound]=useState(false);const[loadError,setLoadError]=useState<string|null>(null);const[retryKey,setRetryKey]=useState(0);const[tab,setTab]=useState<Tab>('info');
  useEffect(()=>{let active=true;void getEjarTenant(accessToken,id).then(r=>{if(!active)return;setData(r);setNotFound(false);setLoadError(null)}).catch(err=>{if(!active)return;if(isNotFoundError(err))setNotFound(true);else setLoadError(err instanceof Error?err.message:'تعذّر تحميل بيانات المستأجر.')});return()=>{active=false}},[accessToken,id,retryKey]);
  if(notFound)return <AppShell title="المستأجر" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><BackButton href="/rent-plus/tenants" label="المستأجرين"/><p className="mt-5 text-text-secondary">المستأجر غير موجود.</p></AppShell>;
  if(loadError)return <AppShell title="المستأجر" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><BackButton href="/rent-plus/tenants" label="المستأجرين"/><div className="mt-5"><DetailLoadError message={loadError} onRetry={()=>setRetryKey(v=>v+1)}/></div></AppShell>;
  return <AppShell title={data?.tenant.name??'المستأجر'} orgName={me.tenant.name_ar} accountType={me.tenant.account_type}>
    {!data?<FormPageSkeleton fields={4} extraCards={1}/>:<div className="flex flex-col gap-4">
      <BackButton href="/rent-plus/tenants" label="المستأجرين"/>
      <Card className="p-3 md:p-6"><div className="flex items-center gap-3"><PersonAvatar name={data.tenant.name} size={56}/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-base font-semibold md:text-lg">{data.tenant.name}</h2><span className="rounded-full bg-surface-subtle px-2.5 py-1 text-xs text-text-secondary">مستأجر</span></div><div className="mt-1 flex flex-wrap gap-2 text-xs text-text-secondary md:text-sm"><span>{data.tenant.party_type==='individual'?'فرد':'منشأة'}</span>{data.tenant.phone&&<span dir="ltr">{data.tenant.phone}</span>}{data.tenant.email&&<span>{data.tenant.email}</span>}</div></div></div></Card>
      <SegmentedToggle value={tab} onChange={setTab} options={[{value:'info',label:'المعلومات'},{value:'contracts',label:'العقود والإيجار'},{value:'payments',label:'الدفعات والأقساط'},{value:'maintenance',label:'الصيانة'}]} className="settings-tabs"/>
      {tab==='info'&&<Card className="p-4 md:p-5"><div className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-text-secondary">الاسم</p><p className="mt-1 font-medium">{data.tenant.name}</p></div><div><p className="text-xs text-text-secondary">النوع</p><p className="mt-1 font-medium">{data.tenant.party_type==='individual'?'فرد':'منشأة'}</p></div><div><p className="text-xs text-text-secondary">الجوال</p><p className="mt-1 font-medium" dir="ltr">{data.tenant.phone??'—'}</p></div><div><p className="text-xs text-text-secondary">البريد الإلكتروني</p><p className="mt-1 font-medium">{data.tenant.email??'—'}</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-input bg-surface-subtle p-3"><p className="text-xs text-text-secondary">العقود</p><p className="mt-1 text-xl font-semibold">{data.contracts.length}</p></div><div className="rounded-input bg-surface-subtle p-3"><p className="text-xs text-text-secondary">الدفعات</p><p className="mt-1 text-xl font-semibold">{data.payments.length}</p></div><div className="rounded-input bg-surface-subtle p-3"><p className="text-xs text-text-secondary">طلبات الصيانة</p><p className="mt-1 text-xl font-semibold">{data.maintenance.length}</p></div></div></Card>}
      {tab==='contracts'&&<div className="grid gap-3">{data.contracts.length===0?<Card className="p-6 text-center text-sm text-text-secondary">لا توجد عقود إيجار مرتبطة بالمستأجر.</Card>:data.contracts.map(c=><a key={c.id} href={`/rent-plus/contracts/${c.id}`}><Card className="p-4 transition-colors hover:border-brand"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">عقد #{c.contract_number}</p><p className="mt-1 text-sm text-text-secondary">{c.lease_contract_assets?.map(a=>a.assets?.name_ar).filter(Boolean).join('، ')||'العقار غير محدد'}</p></div><span className="text-xs text-text-secondary">{contractStatus[c.status]??c.status}</span></div><div className="mt-3 flex flex-wrap justify-between gap-2 text-sm"><span>{date(c.start_date)} — {date(c.end_date)}</span><strong>{money(Number(c.total_value))}</strong></div></Card></a>)}</div>}
      {tab==='payments'&&<div className="grid gap-3 lg:grid-cols-2"><Card className="p-4 md:p-5"><h2 className="mb-3 font-semibold">الأقساط</h2>{data.installments.length===0?<p className="text-sm text-text-secondary">لا توجد أقساط.</p>:<div className="space-y-2">{data.installments.map(i=><div key={i.id} className="flex items-center justify-between gap-3 rounded-input border border-border-subtle p-3"><div><p className="font-medium">قسط #{i.installment_number}</p><p className="text-xs text-text-secondary">استحقاق {date(i.due_date)}</p></div><div className="text-left"><p className="font-semibold">{money(Number(i.amount))}</p><p className="text-xs text-text-secondary">{i.status}</p></div></div>)}</div>}</Card><Card className="p-4 md:p-5"><h2 className="mb-3 font-semibold">الدفعات</h2>{data.payments.length===0?<p className="text-sm text-text-secondary">لا توجد دفعات.</p>:<div className="space-y-2">{data.payments.map(p=><div key={p.id} className="flex items-center justify-between gap-3 rounded-input border border-border-subtle p-3"><div><p className="font-medium">دفعة #{p.payment_number}</p><p className="text-xs text-text-secondary">{date(p.paid_at)}</p></div><strong>{money(Number(p.amount))}</strong></div>)}</div>}</Card></div>}
      {tab==='maintenance'&&<Card className="p-4 md:p-5">{data.maintenance.length===0?<p className="text-sm text-text-secondary">لا توجد طلبات صيانة مرتبطة بعقود هذا المستأجر.</p>:<div className="grid gap-3 md:grid-cols-2">{data.maintenance.map(m=><div key={m.id} className="rounded-input border border-border-subtle p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{m.title}</p><p className="mt-1 text-xs text-text-secondary">طلب #{m.request_number}{m.assets?.name_ar?` · ${m.assets.name_ar}`:''}</p></div><span className="text-xs text-text-secondary">{maintenanceStatus[m.status]??m.status}</span></div><p className="mt-3 text-xs text-text-secondary">{date(m.opened_at)}</p></div>)}</div>}</Card>}
    </div>}
  </AppShell>;
}
