'use client';
import {useMemo,useRef,useState,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import {BrandMark} from '@/components/ui/brand-mark';
import {NAV_ITEMS,isNavGroup} from './nav-items';
function SearchIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-[17px] w-[17px] md:h-[19px] md:w-[19px]"><circle cx="10.5" cy="10.5" r="6.5"/><path d="M20 20l-4.7-4.7"/></svg>}
export function Topbar({title}:{title:string}){const router=useRouter(),input=useRef<HTMLInputElement>(null);const [open,setOpen]=useState(false),[q,setQ]=useState('');
 const pages=useMemo(()=>NAV_ITEMS.flatMap(x=>isNavGroup(x)?x.children:[x]),[]);const results=pages.filter(x=>x.label.includes(q.trim()));useEffect(()=>{if(open)setTimeout(()=>input.current?.focus(),80)},[open]);
 function go(h:string){setOpen(false);setQ('');router.push(h)}
 return <header className="bg-brand md:border-border-subtle md:bg-surface-card relative flex h-20 flex-none items-center gap-2 px-4 pb-5 md:h-[72px] md:gap-4 md:border-b md:px-7 md:pb-0"><div className="md:hidden"><BrandMark width={39} height={17} invert/></div><div className="min-w-0 flex-1 truncate text-[15px] font-semibold text-white md:flex-none md:text-[19px] md:text-text-primary">{title}</div><div className="hidden flex-1 md:block"/>
  <div className="relative flex-none"><div className={`flex items-center overflow-hidden transition-[width,background-color,box-shadow] duration-300 ${open?'bg-surface-card w-[280px] rounded-full shadow-[0_1px_6px_rgba(31,29,34,.11)]':'w-[42px]'} md:h-[42px]`}><button type="button" onClick={()=>setOpen(v=>!v)} aria-label="بحث" className={`flex h-9 w-9 flex-none items-center justify-center rounded-full md:h-[42px] md:w-[42px] ${open?'text-text-primary':'bg-white/15 text-white md:bg-surface-subtle md:text-text-primary'}`}><SearchIcon/></button><div className={`flex min-w-0 flex-1 items-center ${open?'opacity-100':'pointer-events-none opacity-0'}`}><input ref={input} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&results[0])go(results[0].href);if(e.key==='Escape'){setOpen(false);setQ('')}}} placeholder="ابحث في الإدارة..." className="min-w-0 flex-1 bg-transparent text-[13px] text-text-primary outline-none"/><button type="button" onClick={()=>{setOpen(false);setQ('')}} className="me-1 h-8 w-8 rounded-full text-text-secondary">×</button></div></div>{open&&<div className="bg-surface-card border-border-subtle absolute end-0 top-[48px] z-[100] max-h-[320px] w-[min(320px,calc(100vw-32px))] overflow-auto rounded-[18px] border p-2 shadow-[0_12px_36px_rgba(31,29,34,.18)]">{results.length?results.slice(0,10).map(x=><button key={x.href} type="button" onClick={()=>go(x.href)} className="hover:bg-surface-subtle flex w-full rounded-[12px] px-3 py-2.5 text-start text-sm font-medium text-text-primary">{x.label}</button>):<div className="px-3 py-5 text-center text-sm text-text-secondary">لا توجد نتائج</div>}</div>}</div>
 </header>
}