'use client';
import Link from 'next/link';import{useCallback,useEffect,useState}from'react';import{useParams}from'next/navigation';
import{AppShell}from'@/components/layout/app-shell';import{Card}from'@/components/ui/card';import{Button}from'@/components/ui/button';import{useCurrentUser}from'@/lib/auth/current-user-context';import{generateInstallments,getLeaseContract,type InstallmentRow,type LeasePaymentRow,type LeaseContractRow}from'@/lib/api/rent-plus';

const statusLabel:Record<string,string>={draft:'مسودة',upcoming:'قادم',active:'نشط',expired:'منتهي',terminated:'منهى',cancelled:'ملغي',scheduled:'مجدول',partially_paid:'مدفوع جزئيًا',paid:'مدفوع',overdue:'متأخر'};
const money=(v:unknown)=>Number(v??0).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function ContractDetailPage(){
 const{me,accessToken}=useCurrentUser();const{id}=useParams<{id:string}>();type ContractDetail = LeaseContractRow & { financial_summary?:{contract_value?:number;paid_amount?:number;remaining_amount?:number}; lease_contract_assets?:Array<{asset_id:string;assets?:{name_ar?:string}|null}>; lease_contract_parties?:Array<{party_id:string;role:string;parties?:{name?:string}|null}>; lease_installments?:InstallmentRow[]; payments?:LeasePaymentRow[] };
 const[data,setData]=useState<ContractDetail|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await getLeaseContract(accessToken,id);setData(r.contract as ContractDetail)}finally{setLoading(false)}},[accessToken,id]);
 useEffect(()=>{void load()},[load]);
 async function generate(){setBusy(true);try{await generateInstallments(accessToken,id);await load()}finally{setBusy(false)}}
 if(loading)return <AppShell title="تفاصيل العقد" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><Card className="p-8 text-center text-text-secondary">جارٍ تحميل العقد...</Card></AppShell>;
 if(!data)return <AppShell title="تفاصيل العقد" orgName={me.tenant.name_ar} accountType={me.tenant.account_type}><Card className="p-8 text-center">العقد غير موجود</Card></AppShell>;
 const summary=data.financial_summary??{};const assets=data.lease_contract_assets??[];const parties=data.lease_contract_parties??[];const installments=data.lease_installments??[];const payments=data.payments??[];
 return <AppShell title={`العقد ${data.contract_number}`} orgName={me.tenant.name_ar} accountType={me.tenant.account_type}>
  <div className="mb-5 flex items-center justify-between gap-3"><Link href="/rent-plus/contracts" className="text-sm text-brand">← العودة للعقود</Link><span className="rounded-full bg-surface-subtle-3 px-3 py-1 text-xs">{statusLabel[data.status]??data.status}</span></div>
  <div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-sm text-text-secondary">قيمة العقد</p><p className="mt-2 text-xl font-semibold">{money(summary.contract_value)} ر.س</p></Card><Card className="p-5"><p className="text-sm text-text-secondary">المحصل</p><p className="mt-2 text-xl font-semibold">{money(summary.paid_amount)} ر.س</p></Card><Card className="p-5"><p className="text-sm text-text-secondary">المتبقي</p><p className="mt-2 text-xl font-semibold">{money(summary.remaining_amount)} ر.س</p></Card></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-5"><h2 className="mb-4 font-semibold">بيانات العقد</h2><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-text-secondary">البداية</dt><dd>{data.start_date}</dd></div><div><dt className="text-text-secondary">النهاية</dt><dd>{data.end_date}</dd></div><div><dt className="text-text-secondary">المصدر</dt><dd>{data.source}</dd></div><div><dt className="text-text-secondary">دورية الدفع</dt><dd>{data.payment_frequency}</dd></div></dl></Card><Card className="p-5"><h2 className="mb-4 font-semibold">العقارات والأطراف</h2>{assets.map((x)=><p key={x.asset_id} className="mb-2 text-sm">العقار: {x.assets?.name_ar??x.asset_id}</p>)}{parties.map((x)=><p key={x.party_id+x.role} className="mb-2 text-sm">{x.role==='lessor'?'المؤجر':x.role==='lessee'?'المستأجر':x.role}: {x.parties?.name??x.party_id}</p>)}</Card></div>
  <Card className="mt-5 overflow-hidden"><div className="flex items-center justify-between p-5"><h2 className="font-semibold">جدول الاستحقاقات</h2>{installments.length===0&&data.payment_frequency!=='custom'&&<Button onClick={generate} disabled={busy}>{busy?'جارٍ الإنشاء...':'إنشاء الاستحقاقات'}</Button>}</div>{installments.length===0?<p className="px-5 pb-5 text-sm text-text-secondary">لا توجد استحقاقات حتى الآن.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-surface-header text-right text-text-secondary"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">تاريخ الاستحقاق</th><th className="px-4 py-3">القيمة</th><th className="px-4 py-3">المدفوع</th><th className="px-4 py-3">المتبقي</th><th className="px-4 py-3">الحالة</th></tr></thead><tbody>{installments.map((x)=><tr key={x.id} className="border-border-subtle border-t"><td className="px-4 py-3">{x.installment_number}</td><td className="px-4 py-3">{x.due_date}</td><td className="px-4 py-3">{money(x.amount)}</td><td className="px-4 py-3">{money(x.paid_amount)}</td><td className="px-4 py-3">{money(x.remaining_amount)}</td><td className="px-4 py-3">{statusLabel[x.status]??x.status}</td></tr>)}</tbody></table></div>}</Card>
  <Card className="mt-5 overflow-hidden"><div className="p-5"><h2 className="font-semibold">سجل الدفعات</h2></div>{payments.length===0?<p className="px-5 pb-5 text-sm text-text-secondary">لا توجد دفعات مسجلة.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-surface-header text-right text-text-secondary"><tr><th className="px-4 py-3">رقم الدفعة</th><th className="px-4 py-3">المبلغ</th><th className="px-4 py-3">التاريخ</th><th className="px-4 py-3">الطريقة</th><th className="px-4 py-3">الحالة</th></tr></thead><tbody>{payments.map((x)=><tr key={x.id} className="border-border-subtle border-t"><td className="px-4 py-3">{x.payment_number}</td><td className="px-4 py-3">{money(x.amount)}</td><td className="px-4 py-3">{new Date(x.paid_at).toLocaleDateString('ar-SA')}</td><td className="px-4 py-3">{x.payment_method}</td><td className="px-4 py-3">{x.status}</td></tr>)}</tbody></table></div>}</Card>
 </AppShell>
}