import type { NextRequest } from 'next/server';
import { z } from 'zod';
import { ApiError, databaseWriteError, okResponse, withErrorHandling } from '@/lib/http';
import { getAuthenticatedClient } from '@/lib/auth/get-authenticated-client';
import { getCallerContext } from '@/lib/auth/get-caller-context';
interface Ctx{params:Promise<{id:string}>}
const patch=z.object({title:z.string().trim().min(1).max(240).optional(),contract_type:z.string().trim().min(1).max(120).optional(),contract_category:z.string().trim().min(1).max(80).optional(),contract_number:z.string().trim().max(120).nullable().optional(),source:z.enum(['ejar','rega','moj','bank','external','other']).optional(),source_name:z.string().trim().max(120).nullable().optional(),official_reference_number:z.string().trim().max(160).nullable().optional(),official_url:z.string().url().nullable().optional(),status:z.enum(['active','expired','cancelled','terminated','renewed','archived','unknown']).optional(),total_value:z.coerce.number().nonnegative().nullable().optional(),start_date:z.string().date().nullable().optional(),end_date:z.string().date().nullable().optional(),auto_renew:z.boolean().optional(),renewal_period_months:z.coerce.number().int().positive().nullable().optional(),notes:z.string().trim().max(5000).nullable().optional()});
const select='*,contract_parties(*),contract_links(*),contract_documents(*),contract_reminders(*),contract_activity(*)';
export const GET=withErrorHandling<Ctx>(async(req,{params})=>{const{id}=await params;const{supabase}=getAuthenticatedClient(req);const c=await getCallerContext(supabase);const{data,error}=await supabase.from('contracts').select(select).eq('tenant_id',c.tenantId).eq('id',id).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new ApiError(404,'contract_not_found','العقد غير موجود');return okResponse({contract:data});});
export const PATCH=withErrorHandling<Ctx>(async(req,{params})=>{const{id}=await params;const{supabase}=getAuthenticatedClient(req);const c=await getCallerContext(supabase);if(c.role==='agent')throw new ApiError(403,'forbidden','لا تملك صلاحية تعديل العقود');const input=patch.parse(await req.json());if(input.start_date&&input.end_date&&input.end_date<input.start_date)throw new ApiError(400,'invalid_dates','تاريخ النهاية يجب أن يكون بعد البداية');const{data,error}=await supabase.from('contracts').update(input).eq('tenant_id',c.tenantId).eq('id',id).select('*').maybeSingle();if(error)throw databaseWriteError(error,'Failed to update contract');if(!data)throw new ApiError(404,'contract_not_found','العقد غير موجود');await supabase.from('contract_activity').insert({tenant_id:c.tenantId,contract_id:id,actor_user_id:c.userId,action:'updated',details:{fields:Object.keys(input)}});return okResponse({contract:data});});
