import { z } from 'zod';
import { ApiError, databaseWriteError, okResponse, withErrorHandling } from '@/lib/http';
import { getAuthenticatedClient } from '@/lib/auth/get-authenticated-client';
import { getCallerContext } from '@/lib/auth/get-caller-context';
interface Ctx{params:Promise<{id:string}>}
const patch=z.object({title:z.string().trim().min(1).max(240).optional(),contract_type:z.string().trim().min(1).max(120).optional(),contract_category:z.string().trim().min(1).max(80).optional(),contract_number:z.string().trim().max(120).nullable().optional(),source:z.enum(['ejar','rega','moj','bank','external','other']).optional(),source_name:z.string().trim().max(120).nullable().optional(),official_reference_number:z.string().trim().max(160).nullable().optional(),official_url:z.string().url().nullable().optional(),status:z.enum(['active','expired','cancelled','terminated','renewed','archived','unknown']).optional(),total_value:z.coerce.number().nonnegative().nullable().optional(),start_date:z.string().date().nullable().optional(),end_date:z.string().date().nullable().optional(),auto_renew:z.boolean().optional(),renewal_period_months:z.coerce.number().int().positive().nullable().optional(),notes:z.string().trim().max(5000).nullable().optional(),parent_contract_id:z.string().uuid().nullable().optional()});
const select='*,contract_parties(*),contract_links(*),contract_documents(*),contract_reminders(*),contract_activity(*)';
async function enrichLinks(supabase:any,links:any[]){return Promise.all((links??[]).map(async l=>{let label:string|null=null;let href:string|null=null;if(l.link_type==='project'&&l.project_id){const{data}=await supabase.from('projects').select('name_ar').eq('id',l.project_id).maybeSingle();label=data?.name_ar??null;href=`/projects/${l.project_id}`}else if(l.link_type==='asset'&&l.asset_id){const{data}=await supabase.from('assets').select('name_ar,unit_number').eq('id',l.asset_id).maybeSingle();label=data?.name_ar??data?.unit_number??null;href=`/properties/${l.asset_id}`}else if(l.link_type==='lead'&&l.lead_id){const{data}=await supabase.from('leads').select('full_name').eq('id',l.lead_id).maybeSingle();label=data?.full_name??null;href=`/leads/${l.lead_id}`}else if(l.link_type==='listing'&&l.listing_id){const{data}=await supabase.from('listings').select('title_ar,listing_number').eq('id',l.listing_id).maybeSingle();label=data?.title_ar??data?.listing_number??null}else if(l.link_type==='deal'&&l.deal_id){const{data}=await supabase.from('deals').select('deal_type,value,leads(full_name)').eq('id',l.deal_id).maybeSingle();const lead=Array.isArray(data?.leads)?data?.leads[0]:data?.leads;label=data?`${data.deal_type==='rent'?'إيجار':'بيع'} · ${lead?.full_name??'صفقة'}`:null}else if(l.link_type==='party'&&l.party_id){const{data}=await supabase.from('parties').select('name').eq('id',l.party_id).maybeSingle();label=data?.name??null}return{...l,entity_label:label,entity_href:href}}))}
export const GET=withErrorHandling<Ctx>(async(req,{params})=>{const{id}=await params;const{supabase}=getAuthenticatedClient(req);const c=await getCallerContext(supabase);const{data,error}=await supabase.from('contracts').select(select).eq('tenant_id',c.tenantId).eq('id',id).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new ApiError(404,'contract_not_found','العقد غير موجود');data.contract_links=await enrichLinks(supabase,data.contract_links);return okResponse({contract:data});});
export const PATCH=withErrorHandling<Ctx>(async(req,{params})=>{const{id}=await params;const{supabase}=getAuthenticatedClient(req);const c=await getCallerContext(supabase);if(c.role==='agent')throw new ApiError(403,'forbidden','لا تملك صلاحية تعديل العقود');const input=patch.parse(await req.json());if(input.start_date&&input.end_date&&input.end_date<input.start_date)throw new ApiError(400,'invalid_dates','تاريخ النهاية يجب أن يكون بعد البداية');const{data,error}=await supabase.from('contracts').update(input).eq('tenant_id',c.tenantId).eq('id',id).select('*').maybeSingle();if(error)throw databaseWriteError(error,'Failed to update contract');if(!data)throw new ApiError(404,'contract_not_found','العقد غير موجود');await supabase.from('contract_activity').insert({tenant_id:c.tenantId,contract_id:id,actor_user_id:c.userId,action:'updated',details:{fields:Object.keys(input)}});return okResponse({contract:data});});
